Fluorohydride/ygopro-core

operations.cpp

adjust self destroy after MSG_SWAP_CONTROL
fix https://github.com/Fluorohydride/ygopro/issues/1616

fix swap control

---

card.cpp
card.h
interpreter.cpp
libcard.cpp
scriptlib.h

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17912&keyword=&tag=-1
http://yugioh.wikia.com/wiki/Red_Supremacy
The effect of Red Supremacy/レッド・スプレマシー is replacing effect, not getting effect.

add ReplaceEffect

---

card.cpp
interpreter.cpp
libdebug.cpp
scriptlib.h

https://github.com/Fluorohydride/ygopro/issues/1672

add Debug.PreSummon

---

interpreter.cpp

https://github.com/Fluorohydride/ygopro/pull/1781

load script from expansions/script/

---

field.h
interpreter.cpp
libduel.cpp
operations.cpp
processor.cpp
scriptlib.h

Deal with the _Dueltainment_(https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/20AP-JP/c100213060.lua).

add Duel.GetTossedCoinCount and Duel.GetTossedDiceCount

---

card.h
playerop.cpp

https://github.com/Fluorohydride/ygopro/pull/1935

add race Cybers

---

card.cpp
card.h

Description here: https://github.com/Fluorohydride/ygopro/pull/1946

Added TYPE_LINK

---

libcard.cpp

Fix:
https://github.com/Fluorohydride/ygopro/issues/1951#issuecomment-290597459
_T.G. Warwolf_ can Special Summon when Link Monster is Special Summoned.

fix libcard.cpp

---

libcard.cpp

fix card_get_origin_level

---

libcard.cpp

fix card_is_able_to_deck_or_extra_as_cost

---

interpreter.cpp
libduel.cpp
scriptlib.h

Deal with the _Topologic Bomber Dragon_, _Rescue Ferret_ and so on.

add Duel.GetLinkedZone

---

interpreter.cpp
libcard.cpp
scriptlib.h

Deal with the _Ultimaya Tzolkin_, _Phantasmal Lord Ultimitl Bishbaalkin_.

add Card.CheckMZoneFromEX

---

field.cpp
ocgapi.cpp

https://github.com/Fluorohydride/ygopro/pull/1974

Support for both mr4 and mr3 field

---

card.h
processor.cpp

fix https://github.com/Fluorohydride/ygopro/issues/1984

add attack controller change check

---

card.cpp
card.h
field.cpp
field.h
libcard.cpp
libduel.cpp

fix _Auram the World Chalice Blademaster_

update Duel.CheckLocation, Card.IsCanBeSpecialSummoned

---

interpreter.cpp
libcard.cpp
scriptlib.h

Deal with the _V-LAN Hydra_ and _Three Burst Blast Dragon_.

add Card.IsLinkBelow & Card.IsLinkAbove

---

interpreter.cpp
libcard.cpp
scriptlib.h

add Card.GetColumnZone

---

card.cpp
effect.h

Deal with the _F.A. Whip Crosser_.

add EFFECT_CANNOT_TO_GRAVE_AS_COST

---

libcard.cpp

Card.GetColumnZone(c,loc,left,right,tp)
Card.GetLinkedZone(c,tp)
Card.GetMutualLinkedZone(c,tp)
if tp exists, it will return the zone seen by player tp.

Update Card.GetColumnZone & Card.GetLinkedZone & Card.GetMutualLinkedZone

---

interpreter.cpp
libeffect.cpp
scriptlib.h

Effect.UseCountLimit & Effect.CheckCountLimit

---

interpreter.cpp
libcard.cpp
scriptlib.h

Update this: We can use `Card.IsAttack/Defense(X,Y,Z,...)`.

add Card.IsAttack/Defense

---

card.cpp

was missing a case for effect's that redirect to grave.

small adjust to redirect

---

interpreter.cpp

move to gframe by custom script reader.
see Fluorohydride/ygopro#2125

remove load extra scripts from ocgcore

---

card.cpp
card.h
field.cpp
field.h
libcard.cpp
libduel.cpp
processor.cpp

replace #181 
split the commits by different tasks, make the history more trackable.

update attacking process

---

effect.cpp
effect.h
processor.cpp

For the effect https://yugipedia.com/wiki/Raidraptor_-_Wise_Strix

Added EFFECT_QP_ACT_IN_SET_TURN

---

effect.cpp

Fix https://github.com/Fluorohydride/ygopro/issues/2157

fix dec_count

---

operations.cpp

let the player select which card to keep

update unique self destroy

---

field.cpp
processor.cpp

fix #203 and https://github.com/Fluorohydride/ygopro/issues/2176 but skip turn effect don't works well with temp get control effect

temp revert

---

processor.cpp

fix https://github.com/Fluorohydride/ygopro/issues/2211

update magic number

---

effect.cpp
effect.h
libcard.cpp
libduel.cpp
libeffect.cpp

It will be useful for some cards like _Tuner's High_.

multiple effect label

---

field.cpp

for [Hop-Eared Flying Squad](https://yugioh.fandom.com/wiki/Hop-Eared_Flying_Squad)

fix check_tuner_material

---

card.cpp

prevent control loop

---

field.cpp

rebuild desc hint during shuffle hand

---

card.cpp
field.cpp
field.h
libcard.cpp
libduel.cpp
operations.cpp

update Card.IsLinkSummonable and Duel.LinkSummon

---

operations.cpp

automaticity https://github.com/Fluorohydride/ygopro-scripts/commit/ea0e0cb76cb351ea68c37c84f368fdf238b730d2

add chint to opponent's hand

---

card.cpp
card.h
effect.h
field.h
libcard.cpp
libduel.cpp
processor.cpp

solve https://github.com/Fluorohydride/ygopro/issues/2228, https://github.com/Fluorohydride/ygopro-scripts/pull/1061, https://github.com/Fluorohydride/ygopro-scripts/pull/1064

fix&update fusion material

---

card.cpp
card.h
interpreter.cpp
libcard.cpp
scriptlib.h

> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22761
> 「永の王 オルムガンド」のモンスター効果によってエクシーズ素材とするカードを選ぶ際に、モンスタートークンを選ぶ事はできません。
but, _Jormungandr, Generaider Boss of Eternity_ can select equipping tokens.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7967
> 「禁止令」の効果が適用されている場合、そのカード名が宣言されているモンスターを「十二獣の方合」の効果によってデッキから選び、エクシーズ素材とする事自体ができません。
and, forbidden check by default.

add Card.IsCanOverlay

---

operations.cpp

Fix the crash when _Tiki Soul_ use effect when a trap monster is destroyed by battle

fix battle destroy send replace

---

libduel.cpp
operations.cpp

- `Duel.SSet` don't return value.
- `EFFECT_SSET_COST` doesn't apply.

fix Duel.SSet

---

card.cpp
field.cpp

and fix Fluorohydride/ygopro#2233

simplify getting (mutual) linked zone

---

interpreter.cpp
libduel.cpp
scriptlib.h

for https://github.com/Fluorohydride/ygopro/issues/2253

add Duel.ClearOperationInfo

---

effect.h
processor.cpp

part of Fluorohydride/ygopro#2255
related: #97

EFFECT_PIERCE: support double battle damage

---

card.cpp
effect.cpp
field.cpp
field.h
libduel.cpp
operations.cpp
processor.cpp

new ruling

---

processor.cpp

fix problem reported on https://github.com/edo9300/ygopro-core/issues/99

fix disable shuffle check

---

CMakeLists.txt
interpreter.cpp
premake4.lua

https://github.com/Fluorohydride/ygopro/pull/2277

remove lua source

---

effect.h
libcard.cpp
scriptlib.h

@DailyShana @mercury233 
Fluorohydride/ygopro-scripts#1423

Card.CheckUnionTarget()

---

field.cpp

fix https://github.com/Fluorohydride/ygopro-core/issues/329

fix get_draw_count

---

effect.h
libduel.cpp
processor.cpp

https://github.com/Fluorohydride/ygopro-scripts/pull/1481

add EVENT_BREAK_EFFECT

---

card.cpp
common.h

see https://github.com/Fluorohydride/ygopro/issues/2321#issuecomment-699826431

update leave field redirect

---

operations.cpp

https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21444&request_locale=ja

fix get_control

---

operations.cpp

Fix _Child's Play_ vs flip summoning monster which is _Mind Control_ ed

set summon player for filp summon

---

effect.h
field.cpp

```lua
local e2=Effect.CreateEffect(c)
e2:SetType(EFFECT_TYPE_SINGLE)
e2:SetCode(EFFECT_OVERLAY_RITUAL_MATERIAL)
e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
e2:SetRange(LOCATION_MZONE)
e2:SetValue(1)
c:RegisterEffect(e2)
```

add EFFECT_OVERLAY_RITUAL_MATERIAL

---

card.cpp
operations.cpp

fix: https://github.com/Fluorohydride/ygopro/issues/2204

fix EFFECT_DECREASE_TRIBUTE

---

card.cpp
card.h
effect.h
libcard.cpp
scriptlib.h

for _[輪廻独断](https://yu-gi-oh.jp/news_detail.php?page=details&id=1039)_

add Card.GetAttributeInGrave, Card.GetRaceInGrave

---

effectset.h

@mercury233 
std::vector has its internal size, so the size should not be changed manually.
Use std::vector::size().

update struct effect_set_v

---

card.cpp
effect.h
operations.cpp

for the Exorsister cards in DBGC

add EVENT_LEAVE_GRAVE

---

field.cpp
field.h
libduel.cpp
operations.cpp
processor.cpp

https://github.com/Fluorohydride/ygopro-scripts/pull/1719

update Duel.CheckLPCost, Duel.PayLPCost

---

interpreter.cpp

```lua
function GetID()
local offset=self_code<100000000 and 1 or 100
return self_table,self_code,offset
end
```
copied from https://github.com/edo9300/ygopro-core/blob/master/interpreter.cpp#L154

push self_table and self_code to lua for GetID

---

effect.cpp
effect.h
field.cpp
field.h

Fixed the issue with spsummon limit effects like El Shaddoll Winda that spsummon limit counter does not count when the effect is disabled.

Fix limit counter(step 1)

---

interpreter.cpp
interpreter.h
premake5.lua

https://github.com/Fluorohydride/ygopro-core/pull/326
https://github.com/Fluorohydride/ygopro-core/issues/337

update premake5 & basic support for lua5.4

---

card.cpp

for [The Weather Forecast](https://yugipedia.com/wiki/The_Weather_Forecast)

update for szone link

---

field.cpp

for [The Legendary Swordmaster Black Luster Soldier](https://github.com/Fluorohydride/ygopro-pre-script/pull/914/files#diff-4acb4c9a0f61ee93f6cfa83b02fc36e77ced16bafe2f37a2e7c84b234025cd90R62)

fix first turn Duel.GetDrawCount

---

libduel.cpp

eg. activate _Heroic Champion - Claivesolish_ when LP below 500

fix check negative LP cost

---

libduel.cpp
scriptlib.h

before:
```lua
local tg=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS):Filter(Card.IsRelateToEffect,nil,e)
```
after:
```lua
local tg=Duel.GetTargetsRelateToChain()
```

add Duel.GetTargetsRelateToChain

---

card.cpp
card.h
operations.cpp

fix https://github.com/Fluorohydride/ygopro/issues/2438.

fix Card.IsPreviousSetCard

---

card.cpp
card.h
libcard.cpp
scriptlib.h

@mercury233 
fix https://github.com/Fluorohydride/ygopro/issues/2432

add Card.IsCanBeDisabledByEffect()

---

libduel.cpp
scriptlib.h

In consistance with https://github.com/Fluorohydride/ygopro-core/pull/425
@mercury233

Remove unused Duel.GetEnvironment

---

operations.cpp
playerop.cpp

working part of https://github.com/Fluorohydride/ygopro-core/pull/340

cancel spell set from hand

---

libduel.cpp

for https://github.com/Fluorohydride/ygopro-scripts/pull/1535

update Duel.SelectField support extra monster zone

---

card.cpp
effect.h
operations.cpp

update: `EVENT_LEAVE_DECK` need to add for 赫聖の妖騎士.

add EVENT_LEAVE_DECK

---

field.cpp
field.h
libduel.cpp
operations.cpp
scriptlib.h

add these function
- `Duel.GetMustMaterial`: get `EFFECT_MUST_BE_FMATERIAL`, `EFFECT_MUST_BE_SMATERIAL`, `EFFECT_MUST_BE_XMATERIAL` or/and `EFFECT_MUST_BE_LMATERIAL` card(s).
- `Duel.CheckMustMaterial`: check include `EFFECT_MUST_BE_FMATERIAL`, `EFFECT_MUST_BE_SMATERIAL`, `EFFECT_MUST_BE_XMATERIAL` or/and `EFFECT_MUST_BE_LMATERIAL` card(s).

fix must material for Contact "C"

---

card.cpp
card.h
effect.h
field.cpp
libcard.cpp
scriptlib.h

@mercury233 
add EFFECT_TUNER
EFFECT_TUNER
It can be treated as Tuner.
Test replay:
[test_apple.zip](https://github.com/Fluorohydride/ygopro-core/files/10660083/test_apple.zip)
c101112029
Give the token EFFECT_TUNER

add EFFECT_TUNER

---

libduel.cpp

@mercury233 
https://github.com/Fluorohydride/ygopro/issues/2404
add optional parameter: reason_player

update Duel.Destroy, Remove, SendtoGrave, Release

---

field.cpp

fix https://github.com/Fluorohydride/ygopro-scripts/issues/2081

fix field::get_ritual_material

---

field.h
libduel.cpp
operations.cpp
processor.cpp

1. Now count is int32.
2. Add checking in Duel.Check() like what we do in Duel.Damage().

fix field::draw()

---

field.cpp
operations.cpp

fix: Speedroid Ohajikid can target Eccentric Boy.

fix check_tuner_material, select_synchro_material

---

operations.cpp

@mercury233 
erase後要立刻進入下一次迴圈
是我沒注意到 非常抱歉

fix std container erase

---

effect.h
operations.cpp

See https://github.com/Fluorohydride/ygopro-scripts/pull/2368

add EVENT_SPSUMMON_SUCCESS_G_P

---

field.h
operations.cpp
processor.cpp

@mercury233 
I think the main problem of #544 is:
arg1, ..., arg4 should be reserved for arguments, and the processor functions should not change them.
store the data in value1~value4
arg1~arg4 are changed into unsigned since most of them are bit field.

processor_unit: add value1~value4

---

field.cpp
field.h
interpreter.cpp
libduel.cpp
operations.cpp
processor.cpp

@mercury233 
use `nullptr` instead of NULL

use nullptr

---

field.h
playerop.cpp
processor.cpp

The reason player of EVENT_DESTROYED, EVENT_BATTLE_DESTROYED should be the controller in Damage Calculation.

fix EVENT_DESTROYED, EVENT_BATTLE_DESTROYED

---

interpreter.h

C++14
16.2 Source file inclusion
A preprocessing directive of the form
#include < h-char-sequence> new-line
searches a sequence of implementation-defined places for a header identified uniquely by the specified sequence between the < and > delimiters, and causes the replacement of that directive by the entire contents of the header. How the places are specified or the header identified is implementation-defined.
A preprocessing directive of the form
#include " q-char-sequence" new-line
causes the replacement of that directive by the entire contents of the source file identified by the specified sequence between the " delimiters. The named source file is searched for in an implementation-defined manner. 
If this search is not supported, or if the search fails, the directive is reprocessed …

update Lua include

---

common.h
duel.cpp

ygopro is full of crashing caused by unknown reason.
I think `assert` and output to msgbox  on Windows would help.
@mercury233 

use C assert

---

effect.cpp

fixed incorrect reason effect and player of handtrap effects

fix reason_effect of handtrap effect

---

card.cpp
field.h
playerop.cpp

Would show deck sequence for selecting self deck only. Fixes things like this.

hide deck sequence for own deck only

---

common.h
field.h
libgroup.cpp
operations.cpp
playerop.cpp
processor.cpp

- change SIZE_RETURN_VALUE to 512
- change returns.bvalue to uint8 
- update the conclusion in #473 
Now
The max size of select_cards: UINT8_MAX
The max size of cards in response: UINT8_MAX
Cancel in card selection: FF FF FF FF (int -1)
Cancel in card sort: FF (unsigned char UINT8_MAX)
@mercury233 

Change SIZE_RETURN_VALUE to 512

---

field.cpp
field.h
libduel.cpp

Reverts Fluorohydride/ygopro-core#600

Revert "check Kaiser Colosseum in Duel.GetMZoneCount & Duel.GetLocationCountFromEx"

---

interpreter.cpp

fix interpreter.cpp

---

buffer.h
card.cpp
common.h
effect.cpp
field.cpp
field.h
libcard.cpp
libdebug.cpp
libduel.cpp
ocgapi.cpp
operations.cpp

- check sequence in is_location_useable
- check playerid in ocgapi.cpp
@mercury233 

fix Debug.AddCard

---

card.cpp
card.h
common.h

`data.type` (the type in cdb file) does not contain `TYPE_TRAPMONSTER` because it is added by core.
The condition is checked by 
```cpp
if(!(data.type & TYPE_MONSTER))
return FALSE;
```
fix #376

add TYPES_EXTRA_DECK

---

card.cpp

Use constant reference to avoid copying in for loop.
@mercury233

use reference in card::is_affected_by_effect

---

interpreter.cpp
ocgapi.cpp

 fix default_script_reader

---

card.cpp
field.cpp
libduel.cpp
operations.cpp

fix card::xyz_remove

---

duel.cpp
duel.h
field.h
operations.cpp
playerop.cpp
processor.cpp

The result of `process()` is a bit field.
flag: result & PROCESSOR_FLAG
size: result & PROCESSOR_BUFFER_LEN

 add duel::buffer_size() 

---

libeffect.cpp
scriptlib.h

effect::code is not a bit field.

scriptlib: rename to is_effect_has_property

---

card.cpp
effect.h

fix card::is_affect_by_effect

---

duel.cpp
interpreter.cpp
interpreter.h
ocgapi.cpp
ocgapi.h

Before:
load c0.lua
Now:
do not load script

no longer load script for temp card

---

ocgapi.cpp

replaced by strncat
@mercury233 

remove strcpy

---

card.cpp
card.h
card_data.h
playerop.cpp

Now functions in gframe can look up this table.
現在gframe也可以查找這個表
@mercury233 

move second_code to card_data.h

---

premake/lua.lua
premake5.lua

add cidalect, cppdialect

---

ocgapi.h
premake/dll.lua
premake/lua.lua
premake5.lua

see https://github.com/Fluorohydride/ygopro/pull/2767

fix define WIN32

---

premake5.lua

see https://github.com/Fluorohydride/ygopro/pull/2815 and https://github.com/Fluorohydride/ygopro/pull/2816

fix premake link

---

common.h
libdebug.cpp

According to single_mode.cpp
SetAIName
max length: 127 char
ShowHint
max length: 1023 char
@mercury233 

Debug: update SetAIName, ShowHint

---

common.h
duel.cpp
duel.h
field.cpp
mtrandom.h
ocgapi.cpp
ocgapi.h
premake/dll.lua

Reverts Fluorohydride/ygopro-core#760

Revert " Refactor random integer generation and shuffling"

---

common.h
duel.cpp
duel.h
field.cpp
mtrandom.h
ocgapi.cpp
ocgapi.h
premake/dll.lua

Reverts Fluorohydride/ygopro-core#767

Revert "Revert " Refactor random integer generation and shuffling""

---

.github/workflows/build.yml
premake/dll.lua

https://github.com/Fluorohydride/ygopro/pull/2841
https://github.com/Fluorohydride/ygopro/pull/2842

use premake 5.0.0-beta7 & lua 5.4.8

---

mtrandom.h

I am 100% sure that using unary minus is correct.
But maybe I should keep a record in the comment.

update comment and #pragma warning

---

premake/dll.lua
premake5.lua

Let the compiler decide.
@mercury233 

revert cppdialect 

---

field.h
playerop.cpp
processor.cpp

see https://github.com/Fluorohydride/ygopro/pull/2797

update forced in select_chain

---

card.cpp
card_data.h
libduel.cpp

See https://github.com/Fluorohydride/ygopro/pull/2867

Add setcode utility functions

---

card.cpp
field.cpp

fix https://github.com/Fluorohydride/ygopro/issues/2855

Prevent adding activated effects to temp card
