interpreter.cpp, libduel.cpp, operations.cpp
only send pendulum cards to owner's extra deck
建议只考虑把灵摆卡送去持有者的额外卡组，因为规则上不允许额外卡组出现对方的卡，不允许出现表侧的非灵摆类型的卡。
=> SendPtoExtra

operations.cpp
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14248&keyword=&tag=-1
If the activation of Spell/Trap cards is negated, EFFECT_LEAVE_FIELD_REDIRECT should not be applied.
=> fix leave field redirect

effect.h
Specifying the size is mandatory. Fixes the compilation on GCC (debian).
=> Fix illegal enum forward declaration of effect_flag and effect_flag2

effect.h
As @DailyShana pointed out in #27, using `uint64` is absolutely useless since `uint32` is used everywhere else.
=> Change effect_flag size from 8 to 4 bytes

card.cpp
if a non-effect monster gets an effect, it should be treated as an effect monster.
=> fix copy and replace effect

operations.cpp
fix https://github.com/Fluorohydride/ygopro/issues/1640
The returning of trap monsters to field should be treated as follows:
first return to monster zone,
since it is not a monster card now, send it to grave immediately
see http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11586&keyword=&tag=-1
>また、「銀河眼の光子竜」が「アポピスの化神」と戦闘する際に効果を発動した場合、バトルフェイズ終了時にはどちらともフィールド上に戻りますが、フィールド上へ戻ってきた「アポピスの化神」は罠カードとしての扱いのみになり、ただちに墓地へ送られます。
=> fix returning of trap monster

interpreter.cpp
expansions中的脚本应优先读取，以便扩展包实现对OCG效果的修改
例：暗黑圣域、真竜皇V.F.D.
=> change priority of loading scripts

libduel.cpp
fixed the problem from empty list and updated it, now it have that syntax.
Duel.AnnounceLevel(int player[,int min = 1, int max = 12, int exception = nil, ...])
where player declare from a level (number) from min to max, with exception of some (list).
https://github.com/Fluorohydride/ygopro/issues/1700
=> fix & update duel.AnnounceLevel

effect.h, field.cpp, field.h, libduel.cpp, operations.cpp
This effect forces the player to use the zones put as value for a summon/set. This will require to change cards that use `Duel.GetLocationCount` for reasons different from control change and movetofield, like Ground Collapse to use `Duel.GetLocationCount(tp,LOCATION_MZONE,nil,LOCATION_REASON_COUNT)`
=> added EFFECT_FORCE_MZONE

interpreter.cpp
so now we could use #g instead of g:GetCount() to simplify the scripts
=> add metamethod to get the length of Group

interpreter.cpp, libcard.cpp, libduel.cpp, libeffect.cpp, premake4.lua
`lua_tounsigned` is removed in lua 5.3, so we can replace it with `lua_tointeger`
`lua_tointeger` will return 0 on decimal number, so in some place it should use `round(lua_tonumber(...))`
`bit32` it removed in lua 5.3, we can add those codes to utility.lua to avoid mass change of scripts
```lua
--the lua port of bit32 lib, which is removed in lua 5.3
bit={}
function bit.band(a,b)
return a&b
end
function bit.bor(a,b)
return a|b
end
function bit.bxor(a,b)
return a~b
end
function bit.lshift(a,b)
return a<<b
end
function bit.rshift(a,b)
return a>>b
end
function bit.bnot(a)
return ~a
end
local function fieldargs(f,width)
w=width or 1
assert(f>=0,"field cannot be negative")
assert(w>0,"width must be positive")
assert(f+w<=32,"trying to access non-existent bits")
return f,~(-1<<w)
end
function …
```
=> update to lua 5.3

field.h, libduel.cpp, operations.cpp
In libduel, when calling the special summon and change position
functions, the created card_sets were destroyed after the function block
ended, making the lua api crash (this error appears at random in some
builds, i still don't understand why sometimes all works fine and other
times this happens making the client/server crash). In operations
instead there was an out of bound access in the array, leading to the
corruption of other values.
=> Fixed various memory curruption instances

field.cpp
Fix: _Lair of Darkness_ can make cards like _Destiny HERO - Plasma_ release cards from opponent because the val check of `EFFECT_EXTRA_RELEASE_NONSUM` didn't work in `Duel.GetReleaseGroup`.
We should update the script of _Lair of Darkness_ too.
```lua
function c59160188.relval(e,re,r,rp)
return re:IsActivated() and bit.band(r,REASON_COST)~=0
end
```
=> fix check of EFFECT_EXTRA_RELEASE_NONSUM

field.h, libgroup.cpp, playerop.cpp, processor.cpp
`finishable` and `cancelable` will do the same thing: allow the client to send -1 as select result, and in this situation return nil to lua.
The script can try to handle "cancel when part select" by enabling `cancelable`, see the PRs below.
=> fix & update select_unselect_card

playerop.cpp, processor.cpp
Some user may use custom expansion databases, and declare card that only exists in those databases.
Now because the client don't actually support MSG_RETRY, those declaration will break the duel.
So we should make it able to actually retry when the user declare illegal card.
> !system 1421 宣言的卡不符合条件，或无法被主机识别。
=> change announce card behavior

processor.cpp
Now if the sequence of _Iron Dragon Tiamaton_ is moved, the disabled zones aren't changed.
I think this may fix it.
```lua
local e4=Effect.CreateEffect(c)
e4:SetType(EFFECT_TYPE_FIELD)
e4:SetRange(LOCATION_MZONE)
e4:SetCode(EFFECT_DISABLE_FIELD)
e4:SetProperty(EFFECT_FLAG_REPEAT)
e4:SetOperation(c46247282.disop)
c:RegisterEffect(e4)
```
=> update EFFECT_DISABLE_FIELD for Iron Dragon Tiamaton

field.h, operations.cpp
`core.operated_set` will be altered by `move_to_field` if the field spell card is replaced by the cards set, so I use another group in the procedure.
Is there any better way to do this?
=> fix Duel.SSet

duel.cpp
Under C++ standard, type punning is
Undefined Behaviour and strict aliasing rules
forbids writing data to an array of different type,
this is a small change that attempts to fix this issue
by just using std::memcpy, which is effectively
optimized by modern compilers.
=> small mend for undefined behaviour

field.h, operations.cpp, processor.cpp
solve Fluorohydride/ygopro#1831.
The front of core.solving_event maybe not correspond to the solving continuous effect in some situations, so use chain lists to avoid this.
=> update solve continuous

effect.h, processor.cpp
No such timing in the rule.
It was used to implement the continuous effect that only applies during damage calculation.
But continuous effect should be available as long as the condition is satisfied, not becomes available at some timing.
Its usage has been remove from scripts two years ago. see Fluorohydride/ygopro-scripts@c9c9485 and Fluorohydride/ygopro-scripts@7cfab27
~and the commit Fluorohydride/ygopro-scripts@89a8c44 fixed a little gap of effects like _Skyscraper_~.
=> remove EVENT_DAMAGE_CALCULATING

operations.cpp
`ct1` had been wrongly decreased, so in this situation, the last 2 monsters from extra deck will fail to select zone.
=> fix Duel.SpecialSummon(group,...)

card.cpp, libcard.cpp
Update: missing spell counter's ruing.
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14213
質問の状況の場合、「魔導戦士 ブレイカー」は自身の『①：このカードが召喚に成功した場合に発動する。このカードに魔力カウンターを１つ置く（最大１つまで）』モンスター効果によって、これ以上魔力カウンターを置くことができない状態ですが、魔力カウンターを置く事ができる効果を持つカードですので、自分フィールドの魔力カウンターを置く事ができるカードは、モンスターゾーンの「魔導戦士 ブレイカー」と、特殊召喚された「創聖魔導王 エンディミオン」自身と、フィールドゾーンの「魔法都市エンディミオン」の3枚となりますので、1枚～3枚のカードをフィールドから選んで破壊する事になります。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22526
質問の状況の場合、「魔導獣 ケルベロス」は「禁じられた聖杯」の効果によってモンスター効果が無効化されていますが、魔力カウンターを置く事ができる効果を持つカードですので、自分フィールドの魔力カウンターを置く事ができるカードは、モンスターゾーンの「魔導獣 ケルベロス」と、特殊召喚された「創聖魔導王 エンディミオン」自身と、フィールドゾーンの「魔法都市エンディミオン」の3枚となりますので、1枚～3枚のカードをフィールドから選んで破壊する事になります。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22527
質問の状況の場合、ペンデュラムゾーンの「魔導獣 …
=> update Card.IsCanAddCounter and Card.EnableCounterPermit

card.cpp
The `copy_effect` and `replace_effect` would always add `TYPE_EFFECT` for non-effect monsters. This will cause problems when copying spells or traps.
=> add TYPE_EFFECT only for monster when copying effect

card.cpp, field.h, libduel.cpp, operations.cpp
when monster use `EFFECT_SUMMON_PROC`, for extra opportunity of normal summon count, it ignores the zone and releasable parameter of extra summon count, so the scripts of that kind of monsters need update.
This pull request set the parameter internally to avoid updating scripts.
=> update summon proc

libcard.cpp
Them shouldn't return `-2` on card with "?" ATK/DEF in deck. For cards which need to check the "?" ATK/DEF, use `GetTextAttack` instead.
=> update Card.GetAttack and so on

operations.cpp
Fix this: If _Vanity's Emptiness_'s effect replaced by _Generaider Territory_, _Vanity's Emptiness_ don't send to grave.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22792
> この一連の処理後、「虚無空間」は処理が完了したカードとして、**通常罠カードなどのように、墓地へ送られる事になります**。
> （これによって墓地へ送られた永続罠カードは、カードの効果によって墓地へ送られた扱いにはなりません。）
=> fix Duel.ChangeChainOperation

card.cpp, card.h, field.cpp, field.h, libcard.cpp, libduel.cpp, operations.cpp
Fix https://github.com/Fluorohydride/ygopro/issues/2102 and this.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22582
> リンクモンスターである「デリンジャラス・ドラゴン」は通常召喚できないモンスターとして扱われますが、自身のモンスター効果によって墓地から特殊召喚されている「デリンジャラス・ドラゴン」はフィールドを離れる際には表側表示で除外され、裏側表示で除外する事ができませんので、「極超辰醒」を発動する際のコストとして裏側表示で除外するモンスターに、自身のモンスター効果によって墓地から特殊召喚されている「デリンジャラス・ドラゴン」を含める事自体ができません。
=> fix&update remove

field.cpp
fix Fluorohydride/ygopro#2235
`EFFECT_DISABLE_CHAIN` is just like flag effects, we don't need to check whether it is available
=> treat EFFECT_DISABLE_CHAIN as flag effect

processor.cpp
fix Fluorohydride/ygopro#2234
If damage calculation in effect is performed in chain 2, the effects that do not form a chain (like battle destroy replace) should be applied before chain 1.
And it's confirmed that _Heroic Challenger - Thousand Blades_ in grave will miss the timing in this case.
=> fix damage calculation in effect

libduel.cpp
It wasn't even really used in scripts, and the only times it was, tp was set as parameter, even of that isn't really the same as reason player on some cases, thus adding also the possibility of wrong interactions in the long run. Since there's no way to retrieve the reason effect (and even if there was it would have been kinda wasting to call a function to pass it as default parameter) it's better to make it optional
=> Make 2nd parameter in GetLocationCountFromEx optional

operations.cpp, processor.cpp
Similar to special summoning monsters, if the target become not on field or face down, or there is no enough s/t zones, the equipping card should be sent to grave
related: Fluorohydride/ygopro-scripts#1273
=> equip process: send equip card to grave if unable to equip

card.cpp, card.h, effect.cpp, effect.h, operations.cpp
for effect affecting continuous targets, parallel to `EFFECT_TYPE_EQUIP`
Note:
`EFFECT_TYPE_TARGET` is only for effects that **affect** continuous targets. The continuous spell/trap taking continuous targets on field when activating is of this kind, which is different from monster effects that taking continuous targets, see Fluorohydride/ygopro-scripts#1203
Sample:
```lua
local e3=Effect.CreateEffect(c)
e3:SetType(EFFECT_TYPE_TARGET)
e3:SetCode(effect_code)
e3:SetRange(location) --where to apply
--[[other settings:
e3:SetCondition
e3:SetTarget --additional condition of affected continuous target
e3:SetProperty
e3:SetValue
...
--]]
c:RegisterEffect(e3)
```
=> add EFFECT_TYPE_TARGET

card.cpp
_Mass Hypnosis_ will call `refresh_control_status()` twice for each card, so it shouldn't fail this check: https://github.com/Fluorohydride/ygopro-core/pull/205
=> fix refresh control status

card.cpp, card.h, field.cpp, processor.cpp
~There is a defect: if zones are not enough, the destruction is before swapping control.
This is because in some cases, the cards going to be destroyed occupying zones makes no zones to swap control.~
fix https://github.com/Fluorohydride/ygopro/issues/2238
=> fix control adjust

operations.cpp
fixes https://github.com/Fluorohydride/ygopro-core/issues/289
=> Don't cancel attack if monster is switched to def but has EFFECT_DEFENSE_ATTACK

libduel.cpp, scriptlib.h
Before:
```lua
local a=Duel.GetAttacker()
local d=Duel.GetAttackTarget()
if a:IsControler(1-tp) then a,d=d,a end
```
After:
```lua
local a,d=Duel.GetBattleMonster(tp)
```
----
Before:
```lua
local tc=Duel.GetAttacker()
if tc:IsControler(1-tp) then tc=Duel.GetAttackTarget() end
```
After:
```lua
local tc=Duel.GetBattleMonster(tp)
```
----
Before:
```lua
local a=Duel.GetAttacker()
local d=Duel.GetAttackTarget()
return (a:GetControler()==tp and a:IsSetCard(0x33) and a:IsRelateToBattle())
or (d and d:GetControler()==tp and d:IsSetCard(0x33) and d:IsRelateToBattle())
```
After:
```lua
local a=Duel.GetBattleMonster(tp)
return a and a:IsSetCard(0x33) and a:IsRelateToBattle()
```
=> add Duel.GetBattleMonster

libduel.cpp, operations.cpp, processor.cpp
the summon proc in effect should be performed after solving of that effect, fixing following:
- wrong behavior if damage calculation in effect is performed
- summoning monster in chain 1 is affected by continuous effect wrongly #284
=> update summon proc in effect

card.cpp, effect.cpp, effectset.h, field.cpp
@DailyShana  @mercury233 
Problem
[86.zip](https://github.com/Fluorohydride/ygopro-core/files/4776515/86.zip)
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=6890&keyword=&tag=-1
エクシーズ・オーバーディレイ(taeget: No.86 H－C ロンゴミアント with 3+ materials)
Now: No. 86 will not return to Extra Deck.
Correst: No. 86 will return to Extra Deck.
Reason
The status of No.86 is not refreshed after losing its materials.
In current version, Duel.AdjustInstantly(tc) does not work since filter_disable_related_cards() does not check the continuous effects of this.
=> update immune effects

operations.cpp
If under mr4 or lower a trap monster is disabled (via jinzo for example), the monster won't be able to return to its previous location, and will remain stuck in the monster zone, that because the zone locking effect is being reset on RESET_TURN_SET, but the adjust operation isn't refreshing the locations after the effects are reset (like it was doing before the mr5 update). Also, almost all the steps in trap_monster_adjust can be skipped if the duel isn't mr5 as there will always be a free location due to trap monster mechanics in previous master rules.
=> fix trap monsters disabling under duel rule<=4

card.cpp, operations.cpp
@DailyShana @mercury233 
Problem
[unique.zip](https://github.com/Fluorohydride/ygopro-core/files/4807459/unique.zip)
unique1.yrp
Turn 4
Now: マジカルシルクハット cannot special summon 宮廷のしきたり if another one is on the field.
Correct: マジカルシルクハット can special summon 宮廷のしきたり if another one is on the field.
unique2.yrp
Now: Face-down 炎の王 ナグルファー cannot return to field if another one is on the field.
Correct: Face-down 炎の王 ナグルファー can return to field if another one is on the field.
Reason
unique1.yrp
unique2.yrp
It should check uniqueness only when monsters enter the field in face-up position.
=> check unique only for face-up position

operations.cpp
@DailyShana @mercury233 
Problem
Fluorohydride/ygopro-scripts#1434
[reflect.zip](https://github.com/Fluorohydride/ygopro-core/files/4837451/reflect.zip)
reflect.lua(Single mode)
Now: After the effect of RR－レディネス applies, the player still takes damage from EFFECT_REFLECT_DAMAGE.
Correct: After the effect of RR－レディネス applies, the player takes no damage from EFFECT_REFLECT_DAMAGE.
Reason
The system checks EFFECT_CHANGE_DAMAGE before EFFECT_REFLECT_DAMAGE, and the result of EFFECT_REFLECT_DAMAGE will be eexcute directly.
Solution
Now it will check EFFECT_REFLECT_DAMAGE before EFFECT_CHANGE_DAMAGE.
=> change the order of EFFECT_REFLECT_DAMAGE

operations.cpp
fix https://github.com/Fluorohydride/ygopro-scripts/commit/3e3d26d80e6da0f5952d40843d9ba631bf6fc26f
Fusion and ritual effect had checked immune in script.
=> fix send_to by REASON_MATERIAL

operations.cpp
Fix: If _Cyber Dragon_ is destroyed by _Ancient Gear Beast_, and is sent back to hand by other card, it can't special summon,  because it still have `STATUS_DISABLED`
=> refresh disable status after reset effect in send_to

processor.cpp
should also don't process if the monster leave field when the effect resolve
addition to https://github.com/Fluorohydride/ygopro-core/commit/462d1314f5bfa959d042448078dd5394a585b904
=> fix equipped monster activated effect

libduel.cpp, scriptlib.h
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=9227&request_locale=ja
usage:
```lua
function c2732323.spop(e,tp,eg,ep,ev,re,r,rp)
local tc=Duel.GetFirstTarget()
if tc and tc:IsRelateToEffect(e) then
Duel.DisableSelfDestroyCheck()
if Duel.SpecialSummon(tc,0,tp,tp,false,false,POS_FACEUP)>0 then
local a=Duel.GetAttacker()
if a:IsAttackable() and not a:IsImmuneToEffect(e) then
Duel.CalculateDamage(a,tc)
end
end
Duel.DisableSelfDestroyCheck(false)
end
end
```
=> add Duel.DisableSelfDestroyCheck

common.h, operations.cpp
`REASON_LOST_TARGET` is widely used for equip cards but never used for xyz material.
=> define REASON_LOST_OVERLAY

field.cpp
Fix:
- If _Macro Cosmos_ and _Imperial Iron Wall_ are in effect, _Naturia Beast_ can't discard deck as cost.
- If _Dimensional Fissure_ and _Imperial Iron Wall_ are in effect, face-up _Parasite Paracide_ in deck can't be discarded as cost of effect which only discard 1 card from deck.
=> fix Duel.IsPlayerCanDiscardDeckAsCost

group.cpp
prevent crash when calling `GetNext` without `GetFirst`
=> init group.it

card.cpp, processor.cpp
@mercury233 @purerosefallen 
Problem
Continuous effects with code EFFECT_DISABLE_FIELD does not support normal value function.
Reason
card::reset() will set "value" property to 0 when the card enters the field even if "value" is a function.
Since EFFECT_FLAG_FUNC_VALUE is still alive, it becomes a function with reference 0.
It may cause script error when the script tries to call the original value function.
Solution
Now card::reset() will set "value" property to 0 if "value" is a constant.
Therefore, we can use value function in EFFECT_DISABLE_FIELD, just like other effects.
EFFECT_DISABLE_FIELD has 3 types:
1. The player chooses the location
Now:
The script has an operation function but no value function.
The temp value will be set in operation, and it will be reset in card::reset().
2. …
=> fix EFFECT_DISABLE_FIELD

effect.cpp, libcard.cpp
`RESET_SELF_TURN` and `RESET_OPPO_TURN` was using the player who control the card, but at most cases it should be the player who own the effect.
For example, Number 68 used its effect in turn 1 of player A, and its control is got by player B in turn 2, its indes effect should disappear at the end of turn 2, but now it wasn't reset until the turn of the opponent of player B end in turn 3.
=> fix RESET_SELF_TURN RESET_OPPO_TURN

effect.cpp
If _The Prime Monarch_ become equip, is shouldn't activate effect.
=> fix continuous card become equip

card.cpp
Fix: _Archfiend's Staff of Despair_ shouldn't activate the recycle effect if it was equipped and returned to hand but not equipped successfully before destroyed.
=> fix pre_equip_target

libcard.cpp, scriptlib.h
Pendulum card may have different scale in left and right PZONE, such as _変導機咎 クロックアーク_, but most effect refers to only a scale, that should be the current scale.
=> add Card.GetCurrentScale

card.cpp, card.h, libdebug.cpp
Mail in 2019/1/19
Counters with COUNTER_WITHOUT_PERMIT can be put on any monster.
Before:
A card put counters of this type on X:
The counters will not be removed when X is disabled.
A card put counters of this type on itself:
The counters will be removed when the card itself is disabled, the counters put on itself is denoted by COUNTER_NEED_ENABLE.
Now:
A card put counters of this type on itself:
The counters will not be removed when the card itself is disabled.
=> remove COUNTER_NEED_ENABLE

field.cpp, processor.cpp
@mercury233 
Problem
王宮の勅命 is on the field.
Activating a spell card from the field:
The spell card will have STATUS_DISABLED immediately.
Activating a spell card from the hand:
The spell card will not have STATUS_DISABLED immediately.
It may cause the same card has different behaviors when it is activated from different place.
Reason
The disable status is not refreshed when the spell card is moved to the field from the hand.
Solution
Refresh it in step 1.
Test replay
[replay.zip](https://github.com/Fluorohydride/ygopro-core/files/6117863/replay.zip)
=> Refresh disable status for spell activated from hand 

card.cpp, card.h, effect.cpp, effect.h, libcard.cpp, scriptlib.h
@mercury233 
Problem
I. EFFECT_COUNTER_PERMIT should be a continuous effect
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14130&keyword=&tag=-1
The cards with EFFECT_COUNTER_PERMIT can accept Spell Counter after it is resolved.
The player cannot do:
Chain 1: 魔導変換
Chain 2: 魔導加速
This behavior is incorrect, see ddd.
II. 魔力カウンターを置く事ができるカード(cards that can have a Spell Counter)
The term has multiple definitions.
For effects that only put a counter, it means "cards where you can actually put a counter now".
It does NOT contain cards which are disabled or reach their maximum. 
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22526&keyword=&tag=-1
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14213&keyword=&tag=-1
For other effects, it …
=> Update spell counter

processor.cpp
> 「ジェネレイド」と名のついたカードの効果の発動にチェーンして、永続罠カードのカードの発動が行われた際にも、「王の支配」の効果を発動する事はできます。
質問の状況の場合、チェーン3にて発動した「王の支配」の効果が適用され、チェーン2にて発動した「虚無空間」の処理は、『お互いのプレイヤーは、それぞれデッキから１枚ドローする』処理として行われ、最後にチェーン1にて発動した「死の王 ヘル」のモンスター効果によってモンスターが特殊召喚されます。
この一連の処理後、「虚無空間」は処理が完了したカードとして、通常罠カードなどのように、墓地へ送られる事になります。
（これによって墓地へ送られた永続罠カードは、カードの効果によって墓地へ送られた扱いにはなりません。）
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22792&keyword=&tag=-1&request_locale=ja
Fix: The field effect of card whose activate effect is replaced shouldn't be activated, but now _Vanity's Emptiness_ will still prevent summon before it is sent to grave in chain end.
=> don't enable field effect if effect replaced

field.cpp
@mercury233 
Problem
Suppose that a trigger effect X is triggered multiple times in one chain.
When select_chain() is called, there will be multiple chain object with the same effect id.
Since std::sort() is not guaranteed to be stable, we should update chain::chain_operation_sort() when effect id is tied.
Solution
Require #369 
Compare chain_id when tied.
=> update chain::chain_operation_sort() 

card.cpp
ruling can't be confirmed but it must can't go down below 0
=> fix scale below 0

operations.cpp, processor.cpp
@mercury233 @pyrQ
According to
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14155&keyword=&tag=-1
The self-destruction effect will be applied before effect resolution, and this card is sent to grave.
For a continuous card not on the field, the effect resolution will do nothing.
Problem
In this situation, the operation function is still executed.
Reason
`if((peffect->type & EFFECT_TYPE_ACTIVATE) && pcard->is_has_relation(*cait) && !cait->replace_op) {
pcard->enable_field_effect(true);
......
`
`add_process(PROCESSOR_EXECUTE_OPERATION, 0, cait->triggering_effect, 0, cait->triggering_player, 0);`
These lines are executed in the same step.
Even if the self-destruction condition is satisfied, PROCESSOR_EXECUTE_OPERATION will still be executed since it is already in the …
=> fix self-destroy & activation of the card

interpreter.cpp
>When you interact with the Lua API, you are responsible for ensuring consistency. In particular, you are responsible for controlling stack overflow. You can use the function lua_checkstack to ensure that the stack has enough space for pushing new elements.
https://www.lua.org/manual/5.3/manual.html#4.2
-----
Replay: [corrupted stack.zip](https://github.com/Fluorohydride/ygopro-core/files/6434220/corrupted.stack.zip)
In the dueling of this replay, turn 5, the player got `[string "./script/c83764718.lua"]:21: Action is not allowed here.` for _Monster Reborn_, and he activated the first avail card in hand: _Harpie's Feather Duster_.
If you open the replay directly, you may see the player activated _Monster Reborn_ and got MSG_RETRY, but this didn't happened in the duel.
Or sometimes your …
=> check lua stack before pushing

card.cpp
`check_cost_condition` is used by `EFFECT_SUMMON_COST`, `EFFECT_SPSUMMON_COST`, `EFFECT_ATTACK_COST` etc., the `reason_effect` when checking should be set to those effects.
Fix: _Lair of Darkness_ will throw error when _Panther Warrior_ try to attack.
Fix: _Monster Reborn_ will be able to special summon _Tyrant Dragon_ by trying to use tribute with the help of _Lair of Darkness_.
=> fix core.reason_effect for check_cost_condition

field.cpp
Currently extra decks monsters would be put at the end of the extra deck list, thus putting them on top of faceup pendulums that are present in the extra deck, also causing a desync with the client, where the cards will instead be put right below those faceup pendulums. With this the core will have the same behaviour as the client putting the extra deck mosnters below faceup pendulums. Also set cards positions properly to faceup/facedown.
To get this behaviour, use a modified Exchange of the Spirit that calls Debug.ReloadFieldEnd so that the client will get the current internal state from the core, and you'll notice that the top card of the extra deck will be one of the returned extra deck monsters.
```lua
function s.activate(e,tp,eg,ep,ev,re,r,rp)
Duel.SwapDeckAndGrave(tp) …
```
=> Don't put extra deck monsters above faceup pendulums in swap_deck_and_grave

playerop.cpp
_Ground Collapse_ will only disable a zone if the client send the same zone twice as response, which shouldn't happen.
=> fix select_place accept selecting same field twice

operations.cpp
the step 0 of `PROCESSOR_SPSUMMON`, which add the timing hint, was skipped in `Duel.SpecialSummonComplete`
=> fix TIMING_SPSUMMON of Duel.SpecialSummonStep

libdebug.cpp, ocgapi.cpp
@mercury233 
It has been 4 years since New Master Rule came out and 1 year since Master Rule 2020 came out.
In my opinion, the default rule should be set to the current rule.
=> change the default duel_rule to 5

card.cpp, card.h, libcard.cpp, operations.cpp
class card
is_spsummonable(), is_special_summonable(), filter_spsummon_procedure()
They need material info as arguments, but it is passed to those functions by `core.limit_*` now.
Passing the arguments by global variables might cause lots of problems.
Now they will use arguments just like normal functions.
=> add struct material_info

card.cpp, effect.cpp, effect.h, processor.cpp
There are 4 types of bit field in `effect.code`.
1. header + id (28 bits)
2. header + counter_id (16 bits)
3. header + phase_id (12 bits)
4. numeric value, max = 4095
`code & EVENT_PHASE` only works for type 3.
`effect::get_code_type()`
Return: the type of bit field in `code`.
'effect::is_hand_trigger()'
Check if `this` is a event-triggered EFFECT_TYPE_TRIGGER_O in hand or not.
`bool is_continuous_event(uint32 code)`
Check if `code` is an event reserved for EFFECT_TYPE_CONTINUOUS or not
=> add get_code_type()

processor.cpp
The script will use `Duel.Readjust()` if something need to trigger `EVENT_ADJUST` again when processing `EVENT_ADJUST`.
replay: [recursive event trigger detected.zip](https://github.com/Fluorohydride/ygopro-core/files/6799662/recursive.event.trigger.detected.zip)
=> don't trigger EVENT_ADJUST recursively

interpreter.cpp
for https://github.com/Fluorohydride/ygopro/issues/2378
`debug` lib is to be considered, just for `GetID`.
=> Disable `package` lib

libeffect.cpp
Problem: Zoodiac Xyz monster with _Zoodiac Thoroughblade_ as material will be immune from the pierce effect of Thoroughblade if it is affected by _Sky Striker Mecha - Eagle Booster_ .
replay: [immune-x-effect.zip](https://github.com/Fluorohydride/ygopro-core/files/7585330/immune-x-effect.zip)
Eagle Booster check `re:GetOwner()`, which return the Xyz material for `EFFECT_TYPE_XMATERIAL` effects. But the owner of `EFFECT_TYPE_XMATERIAL` effects should be the Xyz monster too.
`effect::get_owner()` is updated [already](https://github.com/Fluorohydride/ygopro-core/commit/96bbbedb6e828f4a227cf5405ed8e284b0def2cc#diff-a8426e607ac7de0872a101095db76189f07562e15ce1b4000ee1e7869827f6f5R659), but `scriptlib::effect_get_owner` [didn't get update](https://github.com/Fluorohydride/ygopro-core/commit/96bb …
=> fix effect:GetOwner

effect.cpp, processor.cpp
@salix5 
There are two problems about the only card in OCG with delayed quick effect: _Droll & Lock Bird_
```lua
Debug.SetAIName("AI")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_PSEUDO_SHUFFLE+DUEL_SIMPLE_AI,5)
Debug.AddCard(94145021,1,1,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(94145021,1,1,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(21076084,0,0,LOCATION_SZONE,0,POS_FACEDOWN)
Debug.AddCard(83968380,0,0,LOCATION_SZONE,1,POS_FACEDOWN)
Debug.AddCard(46986414,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```
The player has 1 _Droll & Lock Bird_ in hand, 1 in deck, his opponent activate _Trickstar Reincarnation_, and chain _Jar of Greed_, after the effects resolved, he should able to …
=> fix delayed quick effect

processor.cpp
fix: if Dragonecro Nethersoul Dragon would be destroyed by battle, Dragonecro Nethersoul Dragon don't activate.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7613&keyword=&tag=-1
> 「冥界龍 ドラゴネクロ」自身が戦闘によって破壊される場合においても、効果が発動します。
> 
> したがって、「冥界龍 ドラゴネクロ」自身が戦闘によって破壊され墓地へ送られる場合であれば、ダメージステップ終了時に墓地へ送られた際に効果が発動します。
because `Card.IsStatus(STATUS_BATTLE_DESTROYED)` was false in `EVENT_DAMAGE_STEP_END`.
=> fix check STATUS_BATTLE_DESTROYED

interpreter.cpp
This lib is also dangerous for accessing Lua internal registry, causing evil access to bad libs.
`GetID` is implemented without debug lib so it's time to ban it
=> Ban Lua debug lib

processor.cpp
Reverts Fluorohydride/ygopro-core#388
Replay: [2.zip](https://github.com/Fluorohydride/ygopro-core/files/7660285/2.zip)
=> Revert "don't trigger EVENT_ADJUST recursively"

operations.cpp
Fix: If the player got no card in deck, them were still able to activate free chain effect in draw phase, but will lose anyways.
=> fix overdraw in draw phase

libduel.cpp
The card activating is location on field, do not need `STATUS_EFFECT_ENABLED`
> Question
自分が手札から発動した「天空の聖域」の【カードの発動】に対して、相手が「サイクロン」をチェーンして発動した場合、さらにチェーンをして自分は「神罰」を発動する事はできますか？
Answer
質問のような状況の場合でも、相手が発動した「サイクロン」にチェーンをして「神罰」を発動する事はできます。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10698&keyword=&tag=-1&request_locale=ja
Now the script of _Divine Punishment_ didn't use `Duel.IsEnvironment`, after this fix it can use that.
=> fix Duel.IsEnvironment

interpreter.cpp
Fix: Shouldn't try to get yield return value from lua when there is nothing pushed to the stack by lua.
Otherwise it will got `invalid index` if `LUA_USE_APICHECK` is defined: https://github.com/Fluorohydride/ygopro/issues/2406
=> fix call_coroutine with no lua return

card.cpp, card.h, effect.h, field.cpp, operations.cpp, processor.cpp
- Fluorohydride/ygopro#2403
- [country1_T3.zip](https://github.com/Fluorohydride/ygopro-core/files/7777310/country1_T3.zip)
The order of calculating original ATK is wrong.
Calculating ATK and DEF separately will cause a lot of problems.
Now ATK and DEF are calculated by
```cpp
get_base_atk_def()
```
```cpp
get_atk_def()
```
at the same time.
---
`EFFECT_FLAG2_OPTION`
The effect of オプション/Gradius' Option
Precedence 1
`EFFECT_FLAG2_WICKED`
The effect of 邪神アバター/The Wicked Avatar, 邪神ドレッド・ルート/The Wicked Dreadroot
Precedence 2
`EFFECT_SWAP_AD`
The effect of スーパーバグマン/Super Crashbug
Precedence 3
---
`EFFECT_SET_BASE_ATTACK_FINAL`
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8149&keyword=&tag=-1
Setting original ATK of itself should be calculated first.
Therefore, changing …
=> fix ATK calculating

field.cpp, field.h, libduel.cpp, scriptlib.h
Currently, `Duel.GetRitualMaterial` will return all monsters which includes xyz and link monsters, causing the calc of ritual level check may be slow.
_Meteonis Drytron_ is the only card which can use monsters without level as ritual tribute, and it will use `Duel.GetRitualMaterialEx`
=> add Duel.GetRitualMaterialEx, update Duel.GetRitualMaterial

card.cpp, card.h, field.cpp, operations.cpp
update: `Card.IsCanBeSpecialSummoned`, `Duel.SpecialSummon` and so on is checking `POS_FACEUP`/`POS_FACEDOWN` only in current version.
`Card.IsCanBeSpecialSummoned`, `Duel.SpecialSummon` and so on can check `POS_ATTACK`/`POS_DEFENSE` in this changes.
Before:
```lua
return c:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_FACEUP_DEFENSE) or c:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_FACEDOWN_DEFENSE)
```
After:
```lua
return c:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_DEFENSE)
```
----
Before:
```lua
local tc=g:GetFirst()
while tc do
local spos=0
if tc:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_FACEUP_DEFENSE) then spos=spos+POS_FACEUP_DEFENSE end
if tc:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_FACEDOWN_DEFENSE) then spos=spos+POS_FACEDOWN_DEFENSE end
if spos~=0 then …
```
=> update for 肆世壊の継承

field.cpp, operations.cpp, processor.cpp
`nil_event`
It is modified by multiple functions for passing arguments.
Passing the arguments by global variables might cause lots of problems.
Now they will use new `tevent` variables.
=> remove argument passing by nil_event

interpreter.cpp
@mercury233 
According to https://github.com/Fluorohydride/ygopro/issues/2378
Should we disable `coroutine` library?
=> disable coroutine library

operations.cpp
Fix: If _Huginn, Wings of the Mysterune_ use its effect to replace the destroy of its equip card, the equip card will be kept on field.
Replay:
[destroy replace and destroy again.zip](https://github.com/Fluorohydride/ygopro-core/files/8456542/destroy.replace.and.destroy.again.zip)
=> fix destroy replace

processor.cpp
Fix: The effect of _Morphing Jar_ won't trigger if its position is set to face-up attack by the effect of _Evil HERO Malicious Fiend_ at the battle phase start
[test_MaliciousFiend.zip](https://github.com/Fluorohydride/ygopro-core/files/8649219/test_MaliciousFiend.zip)
=> fix single trigger effect in battle phase start

libgroup.cpp
make it possible to use nil instead of empty group here
```lua
function c99234526.spcon(e,c)
if c==nil then return true end
local tp=c:GetControler()
return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
and Duel.IsExistingMatchingCard(c99234526.spfilter,tp,LOCATION_GRAVE,0,1,nil)
end
function c99234526.sptg(e,tp,eg,ep,ev,re,r,rp,chk,c)
local g=Duel.GetMatchingGroup(c99234526.spfilter,tp,LOCATION_GRAVE,0,nil)
Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
local tc=g:SelectUnselect(nil,tp,false,true)
if tc then
e:SetLabelObject(tc)
return true
else return false end
end
function c99234526.spop(e,tp,eg,ep,ev,re,r,rp,c)
local g=e:GetLabelObject()
Duel.Remove(g,POS_FACEUP,REASON_COST)
end
```
=> update Group.SelectUnselect to support nil

operations.cpp
fix: if card(s) sent to grave while player had no space in spell&trap zone, `Duel.MoveToField` was returned true.
=> fix move_to_field

field.h, libduel.cpp, operations.cpp, scriptlib.h
Fix1:
If the effect handler don't have releation with the triggering effect, `NegateActivation` and `NegateEffect` shouldn't check immunity.
Example: If _Greedy Venom Fusion Dragon_ activated the 2nd effect, and chained by _Starlight Road_, special summon _Greedy Venom Fusion Dragon_ back to the field and let it be affected by _Tyrant's Temper_, the effect of _Starlight Road_ should still resolve.
Fix2:
See https://github.com/Fluorohydride/ygopro-scripts/pull/1882 and https://github.com/Fluorohydride/ygopro-scripts/pull/1869
=> fix & update Duel.NegateActivation and NegateEffect

libgroup.cpp, scriptlib.h
`Group.CreateGroup` and `Group.FromCards` would be the same behavior as follows:
Would accept any params or none in Card or Group type to form a group.
`Group.AddCard` and `Group.Merge` would be the same behavior as follows:
Would accept any params or none in Card or Group type to add them into the group.
`Group.RemoveCard` and `Group.Sub` would be the same behavior as follows:
Would accept any params or none in Card or Group type to remove them from the group.
=> update CreateGroup, FromCards, AddCard, Merge, RemoveCard, Sub in Group lib

effect.cpp, effect.h, libeffect.cpp, scriptlib.h
Some cards have cost releated to target (_Transmodify_, _Grinning Grave Virus_), but sometime those cards may be used without cost (_Destiny HERO - Diamond Dude_, _Junk Collector_).
Now we are using those codes to make sure the cost is checked:
```lua
function s.cost(e,tp,eg,ep,ev,re,r,rp,chk)
e:SetLabel(100)
return true
end
function s.target(e,tp,eg,ep,ev,re,r,rp,chk)
if chk==0 then
if e:GetLabel()~=100 then return false end
e:SetLabel(0)
return ......
end
e:SetLabel(0)
......
end
```
And it can be shorten to `e:IsCostChecked()`
=> add Effect.IsCostChecked

libcard.cpp, scriptlib.h
For "_手札及び自分フィールドの表側表示のカードの中から_", "_自分の墓地のモンスター及び除外されている自分のモンスターの中から_" effects, cards in hand or grave shouldn't check faceup status.
before:
```lua
return (c:IsLocation(LOCATION_HAND) or c:IsFaceup()) and ...
```
after:
```lua
return c:IsFaceupEx() and ...
```
=> add Card.IsFaceupEx

libduel.cpp, scriptlib.h
Let https://github.com/Fluorohydride/ygopro-scripts/pull/1619 use this instead.
Add this to _Exosister Litania_ will partly fix https://github.com/Fluorohydride/ygopro/issues/2446, but it isn't a good idea to change all cards with effect like that.
=> add Duel.AdjustAll

card.cpp, effect.h
#463
The changes in #408 will reject some normal effects with bit 0xf000.
The effect types have 2 categories:
A. trigger-like
```cpp
EFFECT_TYPE_ACTIVATE
EFFECT_TYPE_TRIGGER_O
EFFECT_TYPE_TRIGGER_F
EFFECT_TYPE_QUICK_O
EFFECT_TYPE_QUICK_F
```
The code is an event.
B. other
The code is an effect code.
Now the check is limited to trigger-like effects.
These effects cannot use continuous_event.
=> fix card::add_effect()

operations.cpp
fix: if Tyrant's Temper and xyz monster with `EFFECT_TYPE_XMATERIAL` effect(e.g. Zoodiac) as material have on the field, `Duel.NegateActivation` and `Duel.NegateEffect` don't check immunity.
> Q.
> 自分フィールドに、「十二獣ラビーナ」をエクシーズ素材としている「十二獣タイグリス」1体と「暴君の威圧」1枚がそれぞれ表側表示で存在しています。
> この状況で、その「十二獣タイグリス」を対象として相手が「死者への手向け」を発動し、チェーンして自分がエクシーズ素材となっている「十二獣ラビーナ」の『●このカードを対象とする相手の魔法カードの効果が発動した時、このカードのX素材を１つ取り除いて発動できる。その発動を無効にする』効果を発動した時、さらにチェーンして相手が「天罰」を発動しました。
> 「暴君の威圧」の効果が適用され「十二獣タイグリス」は罠カードの効果を受けませんが、「天罰」の効果処理はどのようになりますか？
> A.
> ご質問の場合、**「十二獣タイグリス」は罠カードの効果を受けませんので、「天罰」の効果処理は何も行われません**。
> したがって、「死者への手向け」の発動は無効になります。
=> fix Duel.NegateActivation and Duel.NegateEffect

card.cpp, card.h, libcard.cpp, scriptlib.h
fix: if Barrier Statue and/or Vanity's Emptiness has on the field, The Deep Grave cannot activate.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10917&keyword=&tag=-1
> 「[業火の結界像](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=6884)」のモンスター効果が適用されている場合でも、炎属性以外の属性を持つモンスターを対象として、「[深すぎた墓穴](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=13794)」のカードの発動を行う事はできます。
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21861&keyword=&tag=-1
> 「[虚無空間](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=9153)」の効果が適用されている場合でも、「[深すぎた墓穴](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=13794)」のカードの発動を行う事はできます。
but, if `Card.IsCanBeSpecialSummoned` removed in The Deep Grave, The Deep Grave …
=> add Card.IsSpecialSummonableCard

effect.cpp, libeffect.cpp, processor.cpp, scriptlib.h
fix: `Effect.IsCostChecked` return true in case Junk Collector, Trap of Darkness and so on copies normal trap's effect that used `Effect.IsCostChecked`.
(because `Card.CheckActivateEffect` change copied normal trap's `cost_checked`, but doesn't change Junk Collector's `cost_checked`.)
update 1: `Effect.IsCostChecked` can return true when the effect activate (chk=1).
(see https://github.com/Fluorohydride/ygopro-scripts/pull/1931 .)
update 2: add `Effect.SetCostCheck`.
(need by Destiny HERO - Diamond Dude and Serial Spell.)
=> fix & update Effect.IsCostChecked, add Effect.SetCostCheck

libgroup.cpp
If `max` go beyond 127, `arg2` here will exceed int32.
https://github.com/Fluorohydride/ygopro-core/blob/11772de2fa87f561d3b3e276f1e89205664e5cac/libgroup.cpp#L461
But, we still can't select among all cards in a group bigger than 127: https://github.com/Fluorohydride/ygopro-core/pull/449
And, `Group.SelectWithSum...` are not safe for values bigger than 65535: https://github.com/Fluorohydride/ygopro-scripts/pull/1785
BTW, it is the only problem I found in https://github.com/Fluorohydride/ygopro-core/pull/451
=> refuse Group.SelectWithSumEqual with more than 127 max

processor.cpp
修复1：
[根据规则](https://ocg-rule.readthedocs.io/zh_CN/latest/c02/%E5%9F%BA%E6%9C%AC%E7%94%A8%E8%AF%AD.html#id60
)，在抽卡阶段通常抽卡前，只能发动明确记述了抽卡前的效果，不能发自由时点的效果。
而且抽卡前的效果开的连锁结束后，实际抽卡前也不能再开连锁发动其他效果。
但如果发动了效果，就可以连锁包括自由时点效果在内的任意效果。与怪兽召唤中的时点类似。
目前Pro中，在抽卡前的效果连锁处理完毕后，实际抽卡前可以再开连锁发动自由时点的效果。
而且如果场上存在明确记述的抽卡前的效果，但选择不发动，可以在抽卡前“创造时点”发动自由连锁的效果。
为此应把抽卡前的PROCESSOR_POINT_EVENT设置skip_freechain和skip_new。
修复2：
当在skip_freechain的时点发动了效果之后，应可以连锁发动自由时点效果。
目前Pro中，如果这种时点发动了2速效果（例如雷王无效特殊召唤），会再开一个始终不skip_freechain的快速时点
https://github.com/Fluorohydride/ygopro-core/blob/0eec9ae41ae34e3f49a1905d12607d438fc0411d/processor.cpp#L1783
如果没有发动，则继续开skip_freechain的快速时点给对方
https://github.com/Fluorohydride/ygopro-core/blob/0eec9ae41ae34e3f49a1905d12607d438fc0411d/processor.cpp#L1789 …
=> fix EVENT_PREDRAW

field.cpp
According to the Master Rule 2020 changes, F/S/X monsters in extra deck can be summoned to any main monster zones, except for face-up pendulum monsters.
But now in YGOPro all face-up monsters in extra deck will only be summoned to linked zones.
Generally it won't cause problem in duel because there is no way to put non-P F/S/X monster face-up in extra deck, but some single puzzles made earlier than master rule 3 may add cards face-up in extra deck so it won't work even in Master Rule 2020.
=> fix get_rule_zone_fromex

card.cpp, card.h, libcard.cpp
@mercury233 
Card.IsCanBeDisabledByEffect(e, true)
The check for negating monster effect, rejected if the target is `STATUS_DISABLED`.
(The default option)
Ex. 無限泡影
Card.IsCanBeDisabledByEffect(e, false)
The check for negating card effect, rejected if the target is not a Trap Monster and it is `STATUS_DISABLED`.
Ex. エルシャドール・アプカローネ
=> fix Card.IsCanBeDisabledByEffect()

operations.cpp
If _Dragunity Javelin_ use its effect to equip to a monster, it will got `unequip` immediately.
Test puzzle:
```lua
Debug.SetAIName("AI")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_PSEUDO_SHUFFLE+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,2000,0,0)
Debug.SetPlayerInfo(1,2000,0,0)
Debug.AddCard(21249921,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(74701381,0,0,LOCATION_SZONE,2,POS_FACEDOWN)
Debug.AddCard(80549379,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(83986578,1,1,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```
In this situation, Vajrayana won't be treated as has any card equipped.
=> fix EFFECT_TO_GRAVE_REDIRECT_CB

field.cpp
If a ritual monster is summoned and sent to grave, it will has `STATUS_PROC_COMPLETE`, but if it is returned to deck by the effect of _Exchange of the Spirit_, and sent to grave again, it shouldn't has that status.
Test puzzle: [test_SwapDeckAndGrave.zip](https://github.com/Fluorohydride/ygopro-core/files/11474929/test_SwapDeckAndGrave.zip)
=> fix Duel.SwapDeckAndGrave

processor.cpp
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=6373&request_locale=ja
ミュータント・ハイブレイン
Mutant Mindmaster
①：相手フィールドにモンスターが２体以上存在する場合、このカードの攻撃宣言時に、相手フィールドの表側攻撃表示モンスター１体を対象として発動できる。その相手の表側攻撃表示モンスター１体のコントロールをバトルフェイズ終了時まで得る。対象のモンスターはこのターン直接攻撃できず、攻撃可能な場合、相手モンスター１体を攻撃対象として選び、ダメージ計算を行う。 
■「ミュータント・ハイブレイン」の効果が適用された場合、コントロールを得たモンスターが攻撃可能であれば、攻撃対象を選び、ダメージステップに入ります。（戦闘の巻き戻しは発生しません。） 
If `Mutant Mindmaster` activates this effect, the rollback will not occur, and it cannot attack again.
[bug_mutant.zip](https://github.com/Fluorohydride/ygopro-core/files/11279966/bug_mutant.zip)
but_mutant.yrp
Mutant Mindmaster attacks (1st time)
Mutant Mindmaster activates 1st effect
Mutant Mindmaster attacks (2nd time)
I think the reason is `core.attacker->announce_count` does not increase.
Now: …
=> fix Duel.CalculateDamage()

field.h, operations.cpp, processor.cpp
1. The ATK, DEF are int32, but the max of damage is 0xffff.
2. The recover may cause overflow.
1. Now `amount` is put in `arg3`, and it is int32.
2. Now the recover is capped at 
```cpp
int32 limit = INT32_MAX - player[playerid].lp;
```
If `amount` > `limit`, the system will:
- recover `limit` LP
- raise the event `EVENT_RECOVER` with `amount`
=> fix field::recover(), field::damage()

interpreter.cpp
@mercury233 
There are more than 3000 lines in `utility.lua`, and putting all functions in 1 file will make it hard to maintain.
I suggest that we should move Gemini Summon, F/S/X/L Summon, Contact Fusion functions to a new file.
=> add procedure.lua

field.cpp
Mail:
>Q.
バトルフェイズ開始時に自分で「アクションマジック－ダブル・バンキング」を発動し、その後「白闘気白鯨」で戦闘して相手フィールド上の最後のモンスターを破壊した場合、「アクションマジック－ダブル・バンキング」の効果を適用して再度攻撃して直接攻撃することはできますか？
A.
ご質問の場合、「白闘気白鯨」はプレイヤーに直接攻撃できます。
Currently in YGOPro, monster which has "extra attack on monster" can't direct attack again with chain attack effect.
=> fix chain attack

libduel.cpp
Return `0` instead of `nil` if the group is empty, same as other `Duel.` functions
=> update Duel.SSet return

libcard.cpp, scriptlib.h
`c:IsType(TYPE_SPELL+TYPE_RITUAL)`: c is a Spell **or** Ritual card
`c:IsAllTypes(TYPE_SPELL+TYPE_RITUAL)`: c is a Ritual Spell card
=> add more `Card.Is` functions

card.cpp, card.h, libcard.cpp, operations.cpp, scriptlib.h
if activated monster didn't have on the field by itself cost, "When/If this card is Special Summoned by the effect of a monster"'s condition is checked except mzone (ref: https://github.com/Fluorohydride/ygopro-scripts/pull/1916).
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=23826&keyword=&tag=-1
> Question
> 「[輪廻独断](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=16408)」の効果で墓地のモンスターが獣族になっている状況で、天使族である「[丘と芽吹の春化精](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=17418)」の『①：このカードと、モンスター１体または「春化精」カード１枚を手札から捨てて発動できる。デッキから「[丘と芽吹の春化精](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=17418)」以外の「春化精」カード１枚を手札に加える。その後、自分の墓地から地属性モンスター１体を選んで特殊召喚できる』効果を発動し、「[森の聖獣 …
=> add Card.GetSpecialSummonInfo, Card.IsSpecialSummonSetCard

field.h, libduel.cpp, processor.cpp, scriptlib.h
@mercury233 
#482
I think the reason is:
The real condition of 神の宣告/Solemn Judgment is:
The number of ready chain in current chain is 0.
(Ready: the target function has completed.)
Duel.CurrentChain()
The number of chain blocks in current chain.
If Solemn Judgment is copied by another effect, these values will be different.
Duel.GetReadyChain()
The number of ready chain blocks in current chain.
=> add Duel.GetReadyChain

card.cpp, card.h, common.h, field.cpp, field.h, libcard.cpp, libduel.cpp, operations.cpp
EFFECT_CANNOT_RELEASE cannot check reason.
It is necessary for Ritual Beast Ulti-Reirautari (聖霊獣騎 レイラウタリ).
https://github.com/Fluorohydride/ygopro-scripts/pull/2242
target function of EFFECT_CANNOT_RELEASE
Target function:
add 4th param: reason
```lua
function s.rellimit(e,c,tp,r)
return r&REASON_COST~=0
end
```
class Card
Card.IsReleasable 
add 2nd param: reason (optional, default: REASON_COST)
class Duel
CheckReleaseGroup
SelectReleaseGroup
CheckReleaseGroupEx
SelectReleaseGroupEx
add 1st param: reason
GetReleaseGroup
GetReleaseGroupCount
add 3rd param: reason (optional, default: REASON_COST)
IsPlayerCanRelease
add 3rd param: reason (optional, default: REASON_COST)
Now the main reasons are:
`REASON_ACTION`: "This card cannot declare an attack unless"...
`REASON_COST`: The card is …
=> update release functions

card.cpp
fix: _Future Fusion_ can select face-up fusion monster because of `Card.IsFusionSummonableCard` returned true.
> mail:
> Q.
> 「未来融合－フューチャー・フュージョン」の①の効果でお互いに確認する融合モンスターとして、「ペンデュラム・フュージョン」の効果で融合召喚された後にエクストラデッキに表側表示で加わっている「聖菓使クーベル」を選ぶ事はできますか？
> A.
> 「未来融合－フューチャー・フュージョン」の『①』の効果処理として、**エクストラデッキに表側表示で存在する「聖菓使クーベル」を確認することはできません**。
=> fix Card.IsFusionSummonableCard

card.cpp, card.h, libcard.cpp, operations.cpp
@mercury233 @purerosefallen 
Simplify `card::get_code()`, `card::get_another_code()`
`card::second_code`
Now cards with 2 original name are checked by looking up this table.
`data.code`
This is the id in card database, which might be an id of alternative artwork.
The types of card id are:
- cards with 2 original name
Lua table id: data.code
code_rule1: data.code
code_rule2: second_code[data.code]
- always treated as X
Lua table id: data.code
code_rule1: data.alias
code_rule2: 0
- alternative artwork
Lua table id: data.alias (The original card)
code_rule1: data.alias
code_rule2: 0
- other
Lua table id: data.code
code_rule1: data.code
code_rule2: 0
The Lua table id: `card::get_original_code()`
code_rule1, code_rule2: `card::get_original_code_rule()`
Now `data.code` is not sent to Lua …
=> update Card.GetOriginalCode, Card.GetOriginalCodeRule, Card.IsOriginalCodeRule

libcard.cpp
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=19144
■ダメージステップ中にこの効果を発動した場合、**「覇王眷竜」シンクロモンスター１体のシンクロ召喚または「覇王眷竜」エクシーズモンスター１体のエクシーズ召喚を行うことはできません**。
=> fix Card.IsSynchroSummonable, Card.IsXyzSummonable, Card.IsLinkSummonable, Card.IsSummonable, Card.IsMSetable

libduel.cpp
Change the syntax of https://github.com/Fluorohydride/ygopro-core/pull/516 
Change `Duel.CheckReleaseGroup` and `Duel.SelectReleaseGroup` back to the former syntax, remove the `reason` param added in #516, make `REASON_COST` as the reason.
Change `Duel.CheckReleaseGroupEx` to
```Duel.CheckReleaseGroupEx(player,f,count,reason,use_hand,ex,...)```
Change `Duel.SelectReleaseGroupEx` to
```Duel.SelectReleaseGroupEx(player,f,min,max,reason,use_hand,ex,...)```
If the reason of release is not Cost, it should use `Duel.CheckReleaseGroupEx` , which can set reason.
Former we use `Duel.CheckReleaseGroupEx` for checking monster zone + hand, now it requires `use_hand` param to be true.
=> update CheckReleaseGroupEx and so on

processor.cpp
[Q&A 11752](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11752&keyword=&tag=-1&request_locale=ja)
[Q&A 24016](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=24016&keyword=&tag=-1&request_locale=ja)
If a monster meets some effect conditions before or during chain processing, and the control of that monster is transferred later during chain processing, the transferred controller should activate that effect.
Test replay (require https://github.com/Fluorohydride/ygopro-scripts/pull/2358) :
[replay.zip](https://github.com/Fluorohydride/ygopro-core/files/13961055/replay.zip)
=> fix triggering player on control transfer

libgroup.cpp, scriptlib.h
use `Group.SelectSubGroup` :
use `Group.CancelableSelect` :
=> add Group.CancelableSelect

field.h, libduel.cpp, operations.cpp, processor.cpp
@mercury233 
fix https://github.com/Fluorohydride/ygopro-scripts/pull/2246
Before:
- EVENT_SPSUMMON_SUCCESS of summon in Chain Link 1 and EVENT_CHAIN_END are different timing.
(Break Auxiliary.RegisterMergedDelayedEvent)
After:
- They are the same timing.
=> fix: summon in Chain Link 1

operations.cpp
fix: if token(s) was banished, `EVENT_REMOVE` is called.
> _Soul Absorption_
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=75&keyword=&tag=-1
> 「羊トークン」などのモンスタートークンが「[邪帝ガイウス](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=7516)」の効果の対象となる場合、**フィールドを離れる時点で消滅する事となり、結果的にカードが除外された事にはなりません**。
> 
> したがって、質問の状況の場合、**「[魂吸収](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=5850)」の効果は発動しません**。
> 
> _Fish Rain_
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=9786
> ■「オイスタートークン」等のトークンが除外された場合には、**フィールド上から"除外"されずに"消滅"しているため、このカードを発動する事ができません**。
> 
> _Swordsoul Supreme Sovereign - Chengying_
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=16528
> _Ixeep, Omen of the Ghoti_
> …
=> fix EVENT_REMOVE

common.h, duel.cpp, field.h, libcard.cpp, playerop.cpp
Selecting more than 64 cards will crash after #449.
It is because there is only 63 slots in `return_value`.
=> fix: select max capped at SIZE_RETURN_VALUE - 1

playerop.cpp
fix: if `core.select_options` has 256 or more, ygopro broke(but not crash).
=> fix Duel.AnnounceNumber

operations.cpp
It was setting`pcard->temp.reason_effect` twice in 
https://github.com/Fluorohydride/ygopro-core/blob/a04fddec1f78f6e8f18fb5d7d5681e67e4054dbf/operations.cpp#L1272
and
https://github.com/Fluorohydride/ygopro-core/blob/a04fddec1f78f6e8f18fb5d7d5681e67e4054dbf/operations.cpp#L263
Should be similar as `field::destroy(card_set* targets`
https://github.com/Fluorohydride/ygopro-core/blob/a04fddec1f78f6e8f18fb5d7d5681e67e4054dbf/operations.cpp#L212
=> fix EFFECT_SELF_TOGRAVE reason effect

.github/workflows/build.yml
@mercury233 
https://github.com/Fluorohydride/ygopro-core/actions/runs/8564662109
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: marvinpinto/action-automatic-releases@latest. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> The following actions uses node12 which is deprecated and will be forced to run on node16: marvinpinto/action-automatic-releases@latest. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
https://github.com/salix5/action-automatic-releases/commit/75f1a65738686 …
=> update jobs.run to node20

libduel.cpp
fix https://github.com/Fluorohydride/ygopro-scripts/pull/2376
fix crash when calling it without attack monster
>Q.
「禁じられた聖槍」の効果を適用した自分の「白闘気海豚」攻撃のダメージステップが終了した時、「白の輪廻」の効果を発動して攻撃を続けることはできますか？
A.
一例として、「禁じられた聖槍」の効果が適用された自分の「白闘気海豚」で相手の直接攻撃した場合としてご案内いたします。
この場合、ダメージステップ終了時に「白の輪廻」の『②』の効果を発動することはできますが、「白闘気海豚」で再度攻撃することはできません。
=> fix Duel.ChainAttack

card.cpp
Fix summoning trap monster can trigger the effect of _Granguignol the Dusk Dragon_
=> fix special summon status of trap monster

operations.cpp
#334 
#516 
As we have seen before, dividing the reason into effect/cost is not enough.
The reason for release now:
- `REASON_ACTION`
"This card cannot declare an attack unless"... (Panther Warrior)
- `REASON_COST`
The card is released by the cost of effect activation.
Prohibited by `Ritual Beast Ulti-Reirautari`.
- `REASON_EFFECT`
The card is released by effect. (Ritual Summon)
- `REASON_MAINTENANCE`
The maintenance cost. (Aerial Recharge)
- `REASON_SPSUMMON`
The card is released by the Special Summon procedure. (Blue-Eyes Toon Dragon)
- `REASON_SUMMON`
The card is released by Tribute Summon.
- `REASON_RULE`
The card is is released by non-effect actions.  (痛み分け/Share the Pain)
They should be applied to `Duel.Sendto*`, as @465uytrewq suggested in …
=> fix reason check in field::send_to(uint16 step

card.cpp, card.h, effect.cpp, field.cpp, libcard.cpp
Fix syn & xyz summon can use monsters which are being summoned (and summon negated by Rai-Oh) as material
=> add card::is_treated_as_not_on_field

card.cpp, card.h, libcard.cpp, operations.cpp, scriptlib.h
_`send_to` send card to grave before removing overlay cards, so the `previous` `card_state` can't be used_
=> add Card.GetPreviousOverlayCountOnField

field.cpp
After doing `SwapDeckAndGrave` to the deck, it was relying on `shuffle(playerid, LOCATION_DECK)` to reset the sequence of the cards in deck, but if `DUEL_PSEUDO_SHUFFLE` is set, the reset part will be skipped, and the sequence will be wrong.
replay: [deck sequence2.zip](https://github.com/Fluorohydride/ygopro-core/files/15209436/deck.sequence2.zip)
=> fix deck sequence on swap_deck_and_grave

operations.cpp
The effect relation should be cleared on the return to field movement of temp banished monsters, otherwise _Necroface_ can use its 2nd effect when returned by _[Interdimensional Matter Translocator](https://yugipedia.com/wiki/Interdimensional_Matter_Translocator)_
=> fix Duel.ReturnToField clear relate effect

buffer.h, card.cpp, duel.cpp, ocgapi.cpp
https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8
According to the strict aliasing rule, we should not cast a pointer should to another type and dereference.
It can be done by `memcpy`.
C++14
3.10, paragraph 10
> If a program attempts to access the stored value of an object through a glvalue of other than one of the
following types the behavior is undefined:
—(10.1) the dynamic type of the object,
—(10.2) a cv-qualified version of the dynamic type of the object,
—(10.3) a type similar (as defined in 4.4) to the dynamic type of the object,
—(10.4) a type that is the signed or unsigned type corresponding to the dynamic type of the object,
—(10.5) a type that is the signed or unsigned type corresponding to a cv-qualified version of the dynamic type
of the object,
—(10.6) an …
=> fix buffer read/write

card.cpp, card.h, common.h, duel.h, group.h, sort.h
https://en.cppreference.com/w/cpp/container/set
```cpp
template<
class Key,
class Compare = std::less<Key>,
class Allocator = std::allocator<Key>
> class set;
```
https://en.cppreference.com/w/cpp/utility/functional/less
```cpp
constexpr bool operator()( const T& lhs, const T& rhs ) const;
```
The signature of `card_sort` should be:
```cpp
bool operator()(card* const& c1, card* const& c2) const;
```
It is put in a new file `sort.h`, which contains the declaration of incomplete type `card`.
@mercury233 
=> fix struct card_sort::operator()

ocgapi.cpp, ocgapi.h
`pduel->strbuffer` is a C-string, so the parameter should be `char*`.
Related:
https://github.com/Fluorohydride/ygopro/pull/2550
@mercury233 
=> ocgapi: update get_log_message()

card.cpp, interpreter.cpp, interpreter.h, libduel.cpp, operations.cpp, processor.cpp
Fix the following problems of Lua interpreter
The parameter should be a union instead of double casting.
Now it is stored in `union lua_param`.
https://www.lua.org/manual/5.4/manual.html#lua_newthread
Threads are subject to garbage collection, like any Lua object. 
https://www.lua.org/manual/5.4/manual.html#2.5
The only guarantees are that Lua will not collect an object that may still be accessed in the normal execution of the program, and it will eventually collect an object that is inaccessible from Lua. (Here, inaccessible from Lua means that neither a variable nor another live object refer to the object.) Because Lua has no knowledge about C code, it never collects objects accessible through the registry (see [§4.3](https://www.lua.org/manual/5.4/manual.html#4.3)), which includes the …
=> update Lua interpreter

field.h, libduel.cpp, scriptlib.h
Can be used by https://github.com/Fluorohydride/ygopro-scripts/pull/2537/commits/c3a3735fe8c363124f6509201c0f9dbe0bdb2833
=> add Duel.GetLastSelectHint

card.cpp, card.h, effect.cpp, effect.h, field.h, libcard.cpp, libdebug.cpp, operations.cpp, playerop.cpp
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=23486&keyword=&tag=-1&request_locale=ja
counters with `COUNTER_WITHOUT_PERMIT`:
- It can be put on any monster.
- It remains on the card when the card is negated.
ordinary counters:
- It can only be put on the monster with a `EFFECT_COUNTER_PERMIT` effect.
- It is removed when the card is negated.
Now temporary/permanent counter is determined by counter type.
Keeping an array for every counter type is unnecessary.
The number of counter is `uint16` (0~65535), and `returns.svalue` should be the same.
@mercury233 
=> change counter_map to std::map<uint16, uint16>

effectset.h
=> bounds checking in effect_set, effect_set_v

card.cpp, card_data.h, effect.h, interpreter.cpp, interpreter.h, libduel.cpp, libeffect.cpp, scriptlib.cpp
revert to normal assign
std::exchange() will make Read/Write in finding all references unclear, and it might be unnecessary for pointer type.
Add scope operator to ocgapi function call to avoid any potential conflict.
スケープ・ゴート
Scapegoat
73915051
73915052
Sheep Token
Before:
It will try to load script file `c73915052.lua`.
It will run the script and load into c73915052 table if it finds one.
But it will not run `c73915052.initial_effect`.
`utility.lua` and other scripts use some function names as an interface.
Therefore, loading unnecessary functions might cause some problems.
Now:
For `TYPE_NORMAL AND NOT TYPE_PENDULUM` cards, ygopro will not load the script file.
Test:
Add c73915052.lua
```lua
local s,id,o=GetID()
function s.zw_equip_monster(c,tp,tc)
end …
```
=> do not load script for normal monsters

card.cpp
Should always be the player who activate the effect.
> Q.
「ゴブリンドバーグ」が効果を発動し、チェーンして「DNA改造手術」を発動して獣族を宣言し、その後、獣族のその「ゴブリンドバーグ」が「森の聖獣 カラントーサ」を特殊召喚した場合、その「森の聖獣 カラントーサ」の効果を発動することはできますか？
A.
ご質問の場合、「ゴブリンドバーグ」の効果を発動した一連のチェーン処理後に、自分はその「森の聖獣 カラントーサ」の効果を発動できます。
> Q.
自分の「ゴブリンドバーグ」が効果を発動し、「スウィッチヒーロー」をチェーンで発動し、その後、相手がコントロールしていたその「ゴブリンドバーグ」がモンスターを特殊召喚した場合、自分の墓地の「赫焉竜グランギニョル」が②の効果を発動することはできますか？
A.
ご質問の場合、自分は「赫焉竜グランギニョル」の『②』の効果を発動できません。
=> fix spsummon.reason_player

card.cpp, card.h, duel.h, effect.cpp, effect.h, field.cpp, field.h, group.h, interpreter.cpp, interpreter.h, libcard.cpp, libduel.cpp, libgroup.cpp, ocgapi.cpp, operations.cpp, processor.cpp, scriptlib.h
`check_matching` is replaced by `check_filter`, which takes lua_State* as 1st parameter.
This function is usually called from Lua functions like:
```cpp
int32 scriptlib::duel_select_matching_cards(lua_State *L);
```
The arguments are on the stack of L, so the function indices are also the index of L.
d5accce
Avoid unnecessary pointer casting.
A new parameter `scard` is added to  Card.IsNotTuner in 3c46099, and the new parameter is pushed onto the stack before every function call to `check_tuner_material` or`check_synchro_material`.
It will make the stack tracing very hard.
0101614
Because we have the pointer to L now, we can push the synchro monster `pcard` is onto the stack of L before `check_filter`.
It will make the stack tracing easier.
c752dee93a75c440330c9c2f53bd430f478e9c8e
Before: …
=> use ref in PROCESSOR_SELECT_SYNCHRO

card.cpp, common.h, field.cpp, field.h, libduel.cpp, scriptlib.h
In puzzle mode, the player should know the sequence of cards in deck when selecting cards.
-----
`preserve` don't make sense, it should be called **reveal**, and use **hide** as counterpart.
=> update deck sequence

common.h, field.cpp, field.h, libdebug.cpp, ocgapi.cpp, ocgapi.h
list_szone[6], list_szone[7] still exist in current rule.
We can use `Debug.AddCard` to add a card in those zones.
Solution:
player_info::szone_size
The actual size of LOCATION_SZONE in current rule (6 by default).
If the duel is started by MASTER_RULE3, it will become 8.
ocgapi: update signature of start_duel() 
```cpp
extern "C" DECL_DLLEXPORT void start_duel(intptr_t pduel, uint32 options);
```
`options` is a bit field:
0xFFFF0000
duel_rule
0x0000FFFF
duel options
Right shift on signed integer might cause undefined behavior.
@mercury233 
=> ocgapi: update signature of start_duel(), add player_info::szone_size

card.cpp, libcard.cpp
https://db.ygoresources.com/qa#9423
https://db.ygoresources.com/qa#11049
https://db.ygoresources.com/qa#16310
https://db.ygoresources.com/qa#24100
Before:
If the control is changed by an equip card, the control will not return after flipped face-down.
Now:
The control will return.
@mercury233 
=> 24/9/19 change: return control after face-down

effect.cpp, effect.h
`effect::type`
Bit field should be uint32.
```cpp
int32 is_iniital_single() const;
```
Check if it is a EFFECT_TYPE_SINGLE continuous effect created in `initial_effect`.
(A continuous effect owned by the card, not granted by another effect.)
```cpp
bool effect_sort_id(const effect* e1, const effect* e2);
```
According to the mail in #624, continuous effect owned by the card should be applied first.
----
`effect::type`
bit field 應該使用uint32
```cpp
int32 is_iniital_single() const;
```
檢查是否為在initial_effect創建的EFFECT_TYPE_SINGLE永續效果
也就是固有（而不是用其他效果取得）的永續效果
```cpp
bool effect_sort_id(const effect* e1, const effect* e2);
```
根據 #624 的郵件結果，固有的永續效果應該先適用
- 發動DNA移植手術，宣言神屬性
- 召喚 暗黑神鸟 斯摩夫
適用順序：
1. 暗黑神鸟 斯摩夫（固有的永續效果）
2. DNA移植手術
@mercury233 
=> change effect::type to uint32, fix effect_sort_id

card.cpp
#521 
> Ｑ：相手フィールドに《愉怪な燐のきつねびゆらら》が存在している状態で、自分が《ダーク・シムルグ》を特殊召喚した場合、《ダーク・シムルグ》の属性はどのようになりますか？
Ａ：炎属性になります。(24/01/12)
> Ｑ：相手フィールドに《愉怪な燐のきつねびゆらら》が存在している状態で、自分が《ファイアウォール・ドラゴン・ダークフルード－ネオテンペスト》の(2)の効果を発動し、光属性のモンスターを墓地へ送った場合、《ファイアウォール・ドラゴン・ダークフルード－ネオテンペスト》の属性はどのようになりますか？
Ａ：炎属性と光属性になります。(24/01/12)
> Ｑ：もう１度召喚されていない《ナチュラル・ボーン・サウルス》を対象として《千六百七十七万工房》の(1)の効果を発動している状態で、その《ナチュラル・ボーン・サウルス》に《スーペルヴィス》を装備した場合、《ナチュラル・ボーン・サウルス》の種族・属性はどのようになりますか？
Ａ：恐竜族・地属性になります。(24/01/12)
Ｑ：（上記の質問に関連して）装備されていた《スーペルヴィス》が破壊され、《ナチュラル・ボーン・サウルス》がもう１度召喚されていない状態に戻った場合、種族・属性はどのようになりますか？
Ａ：機械族の「光」「闇」「地」「水」「炎」「風」属性として扱います。(24/01/12)
=> Update card::get_attribute() and card::get_race()

card.cpp, effectset.h, operations.cpp
Problem
```lua
--[[message summoning]]
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.AddCard(27125110,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(84117021,0,0,LOCATION_HAND,1,POS_FACEDOWN)
Debug.AddCard(74701381,0,0,LOCATION_SZONE,0,POS_FACEDOWN)
Debug.AddCard(84749824,0,0,LOCATION_SZONE,1,POS_FACEDOWN)
Debug.AddCard(23756165,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(94259633,0,0,LOCATION_EXTRA,0,POS_FACEDOWN)
Debug.AddCard(66570171,1,1,LOCATION_DECK,0,POS_FACEDOWN)
Debug.ReloadFieldEnd()
```
- Activate DNA Surgery (declare: Illusion)
- Activate Spell Wall
- Summon Thousand-Eyes Idol
Now:
Thousand-Eyes Idol is affected by DNA Surgery when checking EFFECT_CANNOT_DISABLE_SUMMON
The summon can be …
=> set STATUS_SUMMONING before checking EFFECT_CANNOT_DISABLE_SUMMON

card.cpp, field.cpp, operations.cpp
- Now the summon is canceled when no procedure is found.
- Now True Draco monsters cannot release spell/trap cards with `STATUS_ACTIVATE_DISABLED`.
@mercury233 
@kiritosoft
=>  cancel summon when no procedure 

README.md, ocgapi.cpp, ocgapi.h
It is a wrapper of `interpreter::load_script` since the beginning of this submodule (2015 Sep).
The signature is misleading because the parameter is actually the script filename.
@mercury233 
=> ocgapi change: preload_script

card.cpp, card.h, field.cpp, libeffect.cpp, operations.cpp, scriptlib.h
Explicitly set type for EFFECT_TYPE_ACTIVATE.
Explicitly set code, type for EFFECT_TYPE_FLIP.
```cpp
static int32 get_effect_property(lua_State* L, effect_member type);
static int32 is_effect_property(lua_State* L, effect_member type);
```
Effect.GetFieldID, GetCode, ...
Effect.IsHasCategory
Now they use the same function.
「叛逆者エト」は１ターンに１度、以下の効果を持つモンスターカードが相手のフィールドか墓地に存在し、LPを半分払った場合のみ手札・墓地から特殊召喚できる。
●効果が発動した時にチェーンして手札かモンスターゾーンで発動する効果
effect filter:
```lua
function filter(e)
return e:GetCode()==EVENT_CHAINING and e:IsHasType(EFFECT_TYPE_QUICK_O) and e:IsHasRange(LOCATION_HAND+LOCATION_MZONE)
end
```
@mercury233 
=>  add Effect.GetRange, IsHasRange 

card.cpp, field.cpp, libduel.cpp, operations.cpp, playerop.cpp, processor.cpp
C99
6.5.7 bitwise-shift-operators
3
> The ***integer promotions*** are performed on each of the operands.
> The type of the result is that of the promoted left operand. 
> If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined.
4 (left shift)
> The result of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are filled with zeros.
> - If E1 has an unsigned type, the value of the result is E1 × 2^E2, reduced modulo one more than the maximum value representable in the result type.
> - If E1 has a signed type and nonnegative value, and E1 × 2^E2 is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.
5 (right shift)
> The result of E1 >> E2 is …
=> update left shift

effect.h
CATEGORY_TOEXTRA			=0x80000000
The category bot field is full now.
To prepare for "card with effect X", we should update to uint64.
Category bit field目前已滿。
為了應對其他的「持有X效果」，建議改成uint64以加入更多類別。
@mercury233 
=> effect: change category to uint64

premake/dll.lua
It is necessary to check if it works in 64 bit environment.
----
保留C4267可以幫助檢查在64位系統是否正常
@mercury233
=> remove disablewarnings C4267

operations.cpp
cherry-pick from #650 
Now Duel.MoveToField() can choose left or right pzone.
Duel.MoveToField()改成可以選擇左或右靈擺區域。
@mercury233 
@jwyxym
=>  move to left or right pzone 

card.cpp, field.h, libduel.cpp, operations.cpp, processor.cpp
```cpp
void raise_event(card* event_card, uint32 event_code, effect* reason_effect, uint32 reason, uint8 reason_player, uint8 event_player, uint32 event_value);
void raise_event(const card_set& event_cards, uint32 event_code, effect* reason_effect, uint32 reason, uint8 reason_player, uint8 event_player, uint32 event_value);
```
Now group version of `raise_event` use a const reference.
The overload resolution will not fail when the first parameter is `nullptr`.
group版本的raise_event改成使用const reference
現在第一個參數傳入nullptr時2個重載版本不再會混淆
@mercury233 
=>  field: change signature of group raise_event 

libduel.cpp
```cpp
for(auto eit = ccard->single_effect.begin(); eit != ccard->field_effect.end(); ++eit)
```
In debug mode, comparing iterator of container A with iterator of container B will cause:
`RunTime Error : map/set iterators incompatible`
在除錯模式中，比較不同容器的迭代器會出現執行階段錯誤
在現在的版本已經沒有必要使用這種寫法
@mercury233 
=>  fix Duel.MajesticCopy 

.github/workflows/build.yml
https://github.com/marvinpinto/actions
This repository has been archived by the owner on May 6, 2024. It is now read-only. 
https://github.com/marvinpinto/actions/commit/40312c52f0ca0d0589b25e8f5172a3613f0759c3
Generating release notes & automatically maintaining releases was much needed when GitHub Actions launched many years ago, but our ecosystem has evolved and there are much better alternatives these days.
For example, the [semantic-release](https://github.com/semantic-release/semantic-release) project + their associated [GitHub Action](https://github.com/semantic-release/github) gives you full control over when releases occur, changelog formatting, custom exec scripts, and much more. Another popular option is the [action-gh-release](https://github.com/softprops/action-gh-release) …
=> use gh-release@v2.1.0

.github/workflows/build.yml
Reverts Fluorohydride/ygopro-core#675
Maybe just wait until it is deprecated.
We can use GitHub CLI after that.
=> Revert "use gh-release@v2.1.0"

.github/workflows/build.yml, .gitignore
- remove -J
https://curl.se/docs/manpage.html#-J
--remote-header-name
WARNING: Exercise judicious use of this option, especially on Windows. A rogue server could send you the name of a DLL or other file that could be loaded automatically by Windows or some third party software.
This option can be dangerous, and it might be unnecessary in this case 
- add -Z
https://curl.se/docs/manpage.html#-Z
-Z, --parallel
Makes curl perform all transfers in parallel as compared to the regular serial manner. Parallel transfer means that curl runs up to N concurrent transfers simultaneously and if there are more than N transfers to handle, it starts new ones when earlier transfers finish.
@mercury233
=> save lua in /temp/

ocgapi.cpp
return LEN_FAIL if not exist
如果序號錯誤，改成返回LEN_FAIL(0)
@mercury233 
=> ocgapi change: return LEN_FAIL if not exist

card.h, field.h, group.h
5.2.10 Reinterpret cast
[expr.reinterpret.cast]
paragraph 7
An object pointer can be explicitly converted to an object pointer of a different type. When a prvalue v of object pointer type is converted to the object pointer type “pointer to cv T”, the result is `static_cast<cv T*>(static_cast<cv void*>(v))`. 
Converting a prvalue of type “pointer to T1” to the type “pointer to T2” (where T1 and T2 are object types and where the alignment requirements of T2 are no stricter than those of T1) and back to its original type yields the original pointer value.
ygopro is full of pointer casting.
Since `effect` is 8 bytes alignment now, `card` and `group` should be 8 bytes alignment.
`card`
`group` 
為了讓指針轉型成立，都改成8對齊
@mercury233 
=>  change cardid to uint64_t 

card.cpp, effect.h
see #709 
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=11294&sort=2&request_locale=ja
光天使スローネ
このカードをX召喚の素材とする場合、モンスター３体以上を素材としたX召喚にしか使用できない。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=11544&request_locale=ja
星因士 カペラ
①：このカードが召喚・反転召喚・特殊召喚に成功した場合に発動できる。このターン自分は、モンスター３体以上を素材としたX召喚をする場合、自分フィールドのレベル４以下の「テラナイト」モンスターをレベル５の素材として扱う事ができる。 
我認為問題是
天座的效果不是改變超量召喚時的等級
因此不該用EFFECT_XYZ_LEVEL 
現在改成
EFFECT_XYZ_LEVEL 
星因士 カペラ
0x3005
3隻以上超量召喚時可以當作5星
EFFECT_XYZ_MIN_COUNT
光天使スローネ
只能用在3隻以上的超量召喚
@mercury233 
----
EFFECT_XYZ_LEVEL 
Satellarknight Capella
0x3005
It can be treated as Level 5  when Xyz Summoning using 3+ monsters
EFFECT_XYZ_MIN_COUNT
Star Seraph Sovereignty
Cannot be used as material for an Xyz Summon, …
=>  fix card::check_xyz_level 

ocgapi.cpp
Now it will only reset core.duel_rule if the value is wrong.
fix #705 
@mercury233
=> fix core.duel_rule in start_duel()

card.cpp, card.h, effect.h, field.cpp
this effect allows xyz or link monsters to use as synchro material, taking value as level.
=> add EFFECT_SYNCHRO_LEVEL_EX

card.cpp, effect.cpp, effect.h, effectset.h, field.cpp, libcard.cpp, libduel.cpp, operations.cpp, processor.cpp
Replace effect_set with std::vector.
C++11 introduces range-based for loop and many std container interfaces, so keeping a user-defined container (which is still a std container inside) is unnecessary.
改成直接使用 std::vector
C++11加入range-based for loop以及各種作用於標準庫容器的函式
現代已經沒有必要使用自定義容器增加維護難度
except b757aa31965f378269ba165553bf7f0bcb0b93ca 
all commits are string replacements.
add_item => push_back
eset.remove_item(i) => eset.erase(eset.begin() + i)
get_last => back
eset.sort() => std::sort(eset.begin(), eset.end(), effect_sort_id);
Reference
https://github.com/edo9300/ygopro-core/commit/be30a5151a9592cd7c129f098c411ad861f94eea
@mercury233 
=>  using effect_set = std::vector<effect*> 

card.h, effect.cpp, effect.h, field.cpp, operations.cpp
fix #724 
Test
```lua
--[[message bug_test]]
Debug.SetAIName("Bug")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.AddCard(4031928,0,0,LOCATION_HAND,0,POS_FACEDOWN_DEFENSE)
Debug.AddCard(7672244,0,0,LOCATION_HAND,1,POS_FACEDOWN_DEFENSE)
Debug.AddCard(86346643,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,0,0,LOCATION_MZONE,1,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(15259703,0,0,LOCATION_SZONE,0,POS_FACEDOWN_DEFENSE)
Debug.AddCard(89631139,0,0,LOCATION_GRAVE,0,POS_FACEUP_ATTACK) …
```
=>  fix EFFECT_COUNT_CODE_SINGLE activation count 

premake/dll.lua, premake/lua.lua
https://premake.github.io/docs/compileas/
lua.lua
- command line options:
use compileas
- files
lua.hpp
This file is for "building in C, including in C++ project"
We compile Lua as C++, so we does not need it.
- removefiles 
src/linit.c
initialization for lua.c
We do not need this file.
src/onelua.c
unnecessary
@mercury233
=> update premake5.lua of Lua

interpreter.cpp
You can choose to define macro `ENABLE_UNSAFE_LIBRARIES` and take full responsibilities for the safety of that branch.
I suggest not, but there is nothing I can do for the safety of such branches.
你可以選擇定義巨集「ENABLE_UNSAFE_LIBRARIES」並對該分支的安全負全部責任。
我建議不要，但是對於這些分支的安全我無能為力。
@mercury233 
@fallenstardust 
@jwyxym 
Reference
https://github.com/edo9300/ygopro-core/pull/126
by @edo9300
=> remove unsafe functions by default

operations.cpp
If the first player had no free zones, and no traps to be adjusted, the step change would've been skipped, having it fall back to the branch where the selected cards from the other return were parsed
=> Fix typo in trap_monster_adjust

operations.cpp
Fix: if the draw count is 0, the `core.overdraw` shouldn't be reset.
Partly fix the scene described in https://github.com/Fluorohydride/ygopro-scripts/pull/2924
=> fix draw 0

ocgapi.cpp, ocgapi.h
- C-compatible header
C does not have `extern "C"`, so we have to change the macro.
```cpp
#ifdef __cplusplus
#define EXTERN_C extern "C"
#else
#define EXTERN_C
#endif
#ifdef _WIN32
#define OCGCORE_API EXTERN_C __declspec(dllexport)
#else
#define OCGCORE_API EXTERN_C __attribute__ ((visibility ("default")))
#endif
```
- default_card_reader, default_message_handler
They are placeholder functions doing nothing.
Now they are changed to static function inside `ocgapi.cpp`.
- add new function default_script_reader
use fopen to read script file
@mercury233 
=> make ocgapi.h a C-compatible header

effect.cpp, effect.h, processor.cpp
workaround fix for https://github.com/Fluorohydride/ygopro/issues/2805
Xyz monster X
material: Zoodiac Ratpier
X activate the effect gained from Zoodiac Ratpier
detach Zoodiac Ratpier
After the chain resolves:
active_handler is NULL
handler->overlay_target is NULL
so get_handler() retrunrs NULL
It cannot be fully solved in current ocgcore structure.
A workaround solution:
last_handler
the last Xyz Monster where the effect is activated
Priority:
active_handler
handler->overlay_target
last_handler
@mercury233 
=> workwround: check last_handler after chain resolution

card.cpp, field.cpp, field.h
[Crystron Cluster nil re.zip](https://github.com/user-attachments/files/20361994/Crystron.Cluster.nil.re.zip)
When checking `EFFECT_LEAVE_FIELD_REDIRECT`, the reason effect should be that instead of the current reason effect.
Btw, advance summon and battle destroy don't have reason effect.
Require https://github.com/Fluorohydride/ygopro-scripts/pull/2953 to work fully.
=> update reason & add reason_effect for field::is_player_can_remove

libdebug.cpp
This reverts commit 26413fcae50693fa60101830e11430be229c90b3.
Single mode:
https://github.com/Fluorohydride/ygopro/blob/d5044ff888e0331659155b049b299340bfc1575a/gframe/single_mode.cpp#L85
preload_script(pduel, filename)
https://github.com/Fluorohydride/ygopro/blob/d5044ff888e0331659155b049b299340bfc1575a/gframe/single_mode.cpp#L129
start_duel(pduel, opt);
start_duel is called after loading the single script, so `szone_size` should be set in `Debug.LoadFieldBegin()`.
fix #782
=> Revert "fix Debug.ReloadFieldBegin (#726)"

card.cpp
If a monster has EFFECT_EXTRA_SYNCHRO_MATERIAL, even if it doesn't meet the value, it should still be able to be synchro material by other materials with effect like EFFECT_HAND_SYNCHRO.
Test puzzle:
```lua
--[[message TEST]]
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_TEST_MODE)
Debug.AddCard(97682931,0,0,LOCATION_HAND,3,POS_FACEUP_ATTACK)
Debug.AddCard(39552864,0,0,LOCATION_MZONE,1,POS_FACEUP_ATTACK)
Debug.AddCard(60071928,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(39552864,0,0,LOCATION_MZONE,3,POS_FACEUP_ATTACK)
Debug.AddCard(821049,0,0,LOCATION_EXTRA,0,POS_FACEDOWN)
Debug.AddCard(55863245,0,0,LOCATION_EXTRA,0,POS_FACEDOWN)
Debug.ReloadFieldEnd()
```
=> Fix EFFECT_EXTRA_SYNCHRO_MATERIAL

card.cpp, operations.cpp
If a Spell/Trap card that is going to have its activation negated leaves the field but it is put back in the S/T zone before this function (`field::negate_chain`) is executed, it should not be sent to the GY when the negation occurs because it is treated as a different copy of the card. Currently it will be sent to the GY, which is wrong
This pull requests adds an extra check for the chain relation before setting the status to the card
test scenario
```
Debug.SetAIName("Negate Activation")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.AddCard(66975205,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(29369059,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(93360904,0,0,LOCATION_HAND,0,POS_FACEDOWN) …
```
=> Fix field negate chain

interpreter.cpp, interpreter.h
https://www.lua.org/manual/5.4/manual.html#luaL_loadbuffer
```c
int luaL_loadbuffer (lua_State *L,
const char *buff,
size_t sz,
const char *name);
```
Equivalent to luaL_loadbufferx with mode equal to NULL.
```c
int luaL_loadbufferx (lua_State *L,
const char *buff,
size_t sz,
const char *name,
const char *mode);
```
The string mode works as in the function lua_load.
https://www.lua.org/manual/5.4/manual.html#lua_load
```c
int lua_load (lua_State *L,
lua_Reader reader,
void *data,
const char *chunkname,
const char *mode);
```
lua_load automatically detects whether the chunk is text or binary and loads it accordingly (see program luac). The string mode works as in function load, with the addition that a NULL value is equivalent to the string "bt". …
=> use text mode in luaL_loadbufferx by default
